CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  username VARCHAR(80) NOT NULL UNIQUE,
  role_name VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  default_view VARCHAR(40) NOT NULL DEFAULT 'dashboard',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_no VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  cluster_name VARCHAR(160) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  share_capital INTEGER NOT NULL DEFAULT 0,
  savings_balance INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE members ADD COLUMN IF NOT EXISTS contact_number VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS birthdate DATE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS civil_status VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS occupation VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS membership_date DATE;

CREATE TABLE IF NOT EXISTS loan_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(40) NOT NULL UNIQUE,
  product_name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  minimum_principal INTEGER NOT NULL DEFAULT 0,
  maximum_principal INTEGER NOT NULL DEFAULT 0,
  minimum_term_months INTEGER NOT NULL DEFAULT 1,
  maximum_term_months INTEGER NOT NULL DEFAULT 1,
  annual_interest_rate_bps INTEGER NOT NULL DEFAULT 0,
  interest_method VARCHAR(40) NOT NULL DEFAULT 'Flat Interest',
  payment_frequency VARCHAR(40) NOT NULL DEFAULT 'Monthly',
  processing_fee INTEGER NOT NULL DEFAULT 0,
  penalty_rate_bps INTEGER NOT NULL DEFAULT 0,
  loans_receivable_account VARCHAR(40) NOT NULL DEFAULT '1050',
  interest_income_account VARCHAR(40) NOT NULL DEFAULT '4010',
  processing_fee_account VARCHAR(40) NOT NULL DEFAULT '4030',
  penalty_income_account VARCHAR(40) NOT NULL DEFAULT '4040',
  cash_account VARCHAR(40) NOT NULL DEFAULT '1010',
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  product_code VARCHAR(40) NOT NULL,
  product_name VARCHAR(160) NOT NULL,
  requested_principal INTEGER NOT NULL DEFAULT 0,
  requested_term_months INTEGER NOT NULL DEFAULT 1,
  purpose TEXT NOT NULL DEFAULT '',
  application_date DATE NOT NULL DEFAULT CURRENT_DATE,
  annual_interest_rate_bps INTEGER NOT NULL DEFAULT 0,
  interest_method VARCHAR(40) NOT NULL,
  payment_frequency VARCHAR(40) NOT NULL,
  processing_fee INTEGER NOT NULL DEFAULT 0,
  penalty_rate_bps INTEGER NOT NULL DEFAULT 0,
  loans_receivable_account VARCHAR(40) NOT NULL,
  interest_income_account VARCHAR(40) NOT NULL,
  processing_fee_account VARCHAR(40) NOT NULL,
  penalty_income_account VARCHAR(40) NOT NULL,
  cash_account VARCHAR(40) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  created_by VARCHAR(80) NOT NULL,
  submitted_by VARCHAR(80),
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS member_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  cluster_name VARCHAR(160) NOT NULL,
  contact_number VARCHAR(60) NOT NULL,
  initial_share_capital INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'Pending Approval',
  created_by VARCHAR(80) NOT NULL,
  approved_by VARCHAR(80),
  approved_member_no VARCHAR(40),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS member_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL UNIQUE,
  source_label VARCHAR(160) NOT NULL DEFAULT 'CSV Paste',
  status VARCHAR(40) NOT NULL DEFAULT 'Staged',
  total_rows INTEGER NOT NULL DEFAULT 0,
  ready_rows INTEGER NOT NULL DEFAULT 0,
  issue_rows INTEGER NOT NULL DEFAULT 0,
  created_by VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS finalized_by VARCHAR(80);
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS imported_rows INTEGER NOT NULL DEFAULT 0;
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS skipped_rows INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS member_import_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL,
  row_no INTEGER NOT NULL,
  member_no VARCHAR(40) NOT NULL DEFAULT '',
  full_name VARCHAR(180) NOT NULL DEFAULT '',
  cluster_name VARCHAR(160) NOT NULL DEFAULT '',
  contact_number VARCHAR(60) NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  birthdate DATE,
  civil_status VARCHAR(40) NOT NULL DEFAULT '',
  occupation VARCHAR(120) NOT NULL DEFAULT '',
  membership_date DATE,
  member_status VARCHAR(30) NOT NULL DEFAULT 'Active',
  row_status VARCHAR(40) NOT NULL DEFAULT 'Ready',
  issues TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_import_rows_batch FOREIGN KEY (import_no)
    REFERENCES member_import_batches (import_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS opening_balance_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL UNIQUE,
  source_label VARCHAR(160) NOT NULL DEFAULT 'CSV Paste',
  status VARCHAR(40) NOT NULL DEFAULT 'Staged',
  total_rows INTEGER NOT NULL DEFAULT 0,
  ready_rows INTEGER NOT NULL DEFAULT 0,
  issue_rows INTEGER NOT NULL DEFAULT 0,
  total_share_capital INTEGER NOT NULL DEFAULT 0,
  total_savings INTEGER NOT NULL DEFAULT 0,
  created_by VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  finalized_by VARCHAR(80),
  finalized_at TIMESTAMPTZ,
  finalized_rows INTEGER NOT NULL DEFAULT 0,
  skipped_rows INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS opening_balance_import_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL,
  row_no INTEGER NOT NULL,
  member_no VARCHAR(40) NOT NULL DEFAULT '',
  member_name VARCHAR(180) NOT NULL DEFAULT '',
  share_capital_opening_balance INTEGER NOT NULL DEFAULT 0,
  savings_opening_balance INTEGER NOT NULL DEFAULT 0,
  cutover_date DATE,
  source_reference VARCHAR(120) NOT NULL DEFAULT '',
  row_status VARCHAR(40) NOT NULL DEFAULT 'Ready',
  issues TEXT NOT NULL DEFAULT '[]',
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  finalized_at TIMESTAMPTZ,
  CONSTRAINT fk_opening_balance_import_rows_batch FOREIGN KEY (import_no)
    REFERENCES opening_balance_import_batches (import_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS initial_member_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  share_capital_amount INTEGER NOT NULL DEFAULT 0,
  membership_fee_amount INTEGER NOT NULL DEFAULT 0,
  savings_deposit_amount INTEGER NOT NULL DEFAULT 0,
  cash_received INTEGER NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS savings_deposits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deposit_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount INTEGER NOT NULL DEFAULT 0,
  cash_received INTEGER NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS share_capital_contributions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contribution_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount INTEGER NOT NULL DEFAULT 0,
  cash_received INTEGER NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS savings_withdrawals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount INTEGER NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  released_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_no VARCHAR(40) NOT NULL UNIQUE,
  source_type VARCHAR(80) NOT NULL,
  source_no VARCHAR(40) NOT NULL,
  description VARCHAR(220) NOT NULL,
  posted_by VARCHAR(80) NOT NULL,
  posted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_no VARCHAR(40) NOT NULL,
  account_code VARCHAR(40) NOT NULL,
  account_name VARCHAR(160) NOT NULL,
  debit INTEGER NOT NULL DEFAULT 0,
  credit INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teller_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no VARCHAR(40) NOT NULL UNIQUE,
  teller_username VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Open',
  opened_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by VARCHAR(80),
  closed_at TIMESTAMPTZ,
  closed_by VARCHAR(80),
  closing_note TEXT,
  expected_cash INTEGER NOT NULL DEFAULT 0,
  actual_cash INTEGER NOT NULL DEFAULT 0,
  variance INTEGER NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  variance_note TEXT,
  variance_noted_by VARCHAR(80),
  variance_noted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS teller_cash_counts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  expected_cash INTEGER NOT NULL DEFAULT 0,
  actual_cash INTEGER NOT NULL DEFAULT 0,
  variance INTEGER NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  submitted_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Submitted',
  submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
