CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  username VARCHAR(80) NOT NULL UNIQUE,
  role_name VARCHAR(120) NOT NULL,
  additional_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  default_view VARCHAR(40) NOT NULL DEFAULT 'dashboard',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS additional_roles JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_no VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  cluster_name VARCHAR(160) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  share_capital NUMERIC(18,2) NOT NULL DEFAULT 0,
  savings_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE members ADD COLUMN IF NOT EXISTS contact_number VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS birthdate DATE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS civil_status VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS occupation VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS membership_date DATE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS previous_loan_balance NUMERIC(18,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS member_previous_loans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_no VARCHAR(40) NOT NULL,
  loan_label VARCHAR(160) NOT NULL DEFAULT '',
  application_date DATE,
  outstanding_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  created_by VARCHAR(80) NOT NULL DEFAULT '',
  updated_by VARCHAR(80) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO member_previous_loans (
  member_no, loan_label, application_date, outstanding_balance, notes, created_by, updated_by
)
SELECT member_no, 'Previous Loan Balance', NULL, previous_loan_balance,
       'Migrated from single previous loan balance field.', 'migration', 'migration'
FROM members
WHERE previous_loan_balance > 0
  AND NOT EXISTS (
    SELECT 1
    FROM member_previous_loans existing
    WHERE existing.member_no = members.member_no
  );

UPDATE members
SET cluster_name = CASE cluster_name
  WHEN 'Market Vendors Cluster' THEN 'REGULAR MEMBERS CAPTURE'
  WHEN 'Rice Farmers Cluster' THEN 'REGULAR MEMBERS NON CAPTURE'
  WHEN 'Teachers Cluster' THEN 'REGULAR MEMBERS LGU'
  WHEN 'General Membership' THEN 'COMMUNITY A MEMBERS'
  WHEN 'Water Station Group' THEN 'COMMUNITY B MEMBERS'
  ELSE cluster_name
END
WHERE cluster_name IN (
  'Market Vendors Cluster',
  'Rice Farmers Cluster',
  'Teachers Cluster',
  'General Membership',
  'Water Station Group'
);

CREATE TABLE IF NOT EXISTS loan_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(40) NOT NULL UNIQUE,
  product_name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  minimum_principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  maximum_principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  minimum_term_months INTEGER NOT NULL DEFAULT 1,
  maximum_term_months INTEGER NOT NULL DEFAULT 1,
  annual_interest_rate_bps INTEGER NOT NULL DEFAULT 0,
  interest_method VARCHAR(40) NOT NULL DEFAULT 'Flat Interest',
  payment_frequency VARCHAR(40) NOT NULL DEFAULT 'Monthly',
  processing_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  service_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_rate_bps INTEGER NOT NULL DEFAULT 0,
  savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_optional BOOLEAN NOT NULL DEFAULT FALSE,
  penalty_rate_bps INTEGER NOT NULL DEFAULT 0,
  loans_receivable_account VARCHAR(40) NOT NULL DEFAULT '1050',
  interest_income_account VARCHAR(40) NOT NULL DEFAULT '4010',
  processing_fee_account VARCHAR(40) NOT NULL DEFAULT '4030',
  insurance_income_account VARCHAR(40) NOT NULL DEFAULT '4050',
  share_capital_account VARCHAR(40) NOT NULL DEFAULT '3010',
  savings_account VARCHAR(40) NOT NULL DEFAULT '2020',
  penalty_income_account VARCHAR(40) NOT NULL DEFAULT '4040',
  cash_account VARCHAR(40) NOT NULL DEFAULT '1010',
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  product_code VARCHAR(40) NOT NULL,
  product_name VARCHAR(160) NOT NULL,
  requested_principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  requested_term_months INTEGER NOT NULL DEFAULT 1,
  purpose TEXT NOT NULL DEFAULT '',
  collateral_type VARCHAR(30) NOT NULL DEFAULT 'PDC',
  application_date DATE NOT NULL DEFAULT CURRENT_DATE,
  annual_interest_rate_bps INTEGER NOT NULL DEFAULT 0,
  interest_method VARCHAR(40) NOT NULL,
  payment_frequency VARCHAR(40) NOT NULL,
  processing_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  service_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_rate_bps INTEGER NOT NULL DEFAULT 0,
  savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_optional BOOLEAN NOT NULL DEFAULT FALSE,
  penalty_rate_bps INTEGER NOT NULL DEFAULT 0,
  loans_receivable_account VARCHAR(40) NOT NULL,
  interest_income_account VARCHAR(40) NOT NULL,
  processing_fee_account VARCHAR(40) NOT NULL,
  insurance_income_account VARCHAR(40) NOT NULL DEFAULT '4050',
  share_capital_account VARCHAR(40) NOT NULL DEFAULT '3010',
  savings_account VARCHAR(40) NOT NULL DEFAULT '2020',
  penalty_income_account VARCHAR(40) NOT NULL,
  cash_account VARCHAR(40) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  created_by VARCHAR(80) NOT NULL,
  submitted_by VARCHAR(80),
  submitted_at TIMESTAMPTZ,
  credit_assessment_notes TEXT NOT NULL DEFAULT '',
  recommended_principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  recommended_term_months INTEGER NOT NULL DEFAULT 0,
  decision VARCHAR(30),
  decision_remarks TEXT NOT NULL DEFAULT '',
  decision_date DATE,
  decided_by VARCHAR(80),
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_document_forms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  form_data TEXT NOT NULL DEFAULT '{}',
  created_by VARCHAR(80) NOT NULL DEFAULT '',
  updated_by VARCHAR(80) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS credit_assessment_notes TEXT NOT NULL DEFAULT '';
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS collateral_type VARCHAR(30) NOT NULL DEFAULT 'PDC';
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS recommended_principal INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS recommended_term_months INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS decision VARCHAR(30);
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS decision_remarks TEXT NOT NULL DEFAULT '';
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS decision_date DATE;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS decided_by VARCHAR(80);
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS decided_at TIMESTAMPTZ;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS service_fee_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS cbu_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS cbu_optional BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS insurance_income_account VARCHAR(40) NOT NULL DEFAULT '4050';
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS share_capital_account VARCHAR(40) NOT NULL DEFAULT '3010';
ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS savings_account VARCHAR(40) NOT NULL DEFAULT '2020';

CREATE TABLE IF NOT EXISTS loans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_no VARCHAR(40) NOT NULL UNIQUE,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  product_code VARCHAR(40) NOT NULL,
  product_name VARCHAR(160) NOT NULL,
  principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  term_months INTEGER NOT NULL DEFAULT 1,
  annual_interest_rate_bps INTEGER NOT NULL DEFAULT 0,
  interest_method VARCHAR(40) NOT NULL,
  payment_frequency VARCHAR(40) NOT NULL,
  processing_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  service_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  insurance_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  cbu_rate_bps INTEGER NOT NULL DEFAULT 0,
  cbu_applied BOOLEAN NOT NULL DEFAULT FALSE,
  savings_retention_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0,
  total_interest NUMERIC(18,2) NOT NULL DEFAULT 0,
  total_payable NUMERIC(18,2) NOT NULL DEFAULT 0,
  net_proceeds NUMERIC(18,2) NOT NULL DEFAULT 0,
  installment_count INTEGER NOT NULL DEFAULT 0,
  first_payment_date DATE NOT NULL,
  maturity_date DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'For Release',
  computed_by VARCHAR(80) NOT NULL,
  computed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_installments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_no VARCHAR(40) NOT NULL,
  installment_no INTEGER NOT NULL,
  due_date DATE NOT NULL,
  principal_due NUMERIC(18,2) NOT NULL DEFAULT 0,
  interest_due NUMERIC(18,2) NOT NULL DEFAULT 0,
  total_due NUMERIC(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (loan_no, installment_no)
);

CREATE TABLE IF NOT EXISTS loan_releases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_no VARCHAR(40) NOT NULL UNIQUE,
  loan_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  principal NUMERIC(18,2) NOT NULL DEFAULT 0,
  processing_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  insurance_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  cbu_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  savings_retention_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  net_proceeds NUMERIC(18,2) NOT NULL DEFAULT 0,
  cash_released NUMERIC(18,2) NOT NULL DEFAULT 0,
  release_date DATE NOT NULL,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  released_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_collections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_no VARCHAR(40) NOT NULL UNIQUE,
  loan_no VARCHAR(40) NOT NULL,
  installment_no INTEGER NOT NULL,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  principal_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  interest_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  amount_received NUMERIC(18,2) NOT NULL DEFAULT 0,
  collection_date DATE NOT NULL,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS member_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  cluster_name VARCHAR(160) NOT NULL,
  contact_number VARCHAR(60) NOT NULL,
  initial_share_capital NUMERIC(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'Pending Approval',
  created_by VARCHAR(80) NOT NULL,
  approved_by VARCHAR(80),
  approved_member_no VARCHAR(40),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

UPDATE member_applications
SET cluster_name = CASE cluster_name
  WHEN 'Market Vendors Cluster' THEN 'REGULAR MEMBERS CAPTURE'
  WHEN 'Rice Farmers Cluster' THEN 'REGULAR MEMBERS NON CAPTURE'
  WHEN 'Teachers Cluster' THEN 'REGULAR MEMBERS LGU'
  WHEN 'General Membership' THEN 'COMMUNITY A MEMBERS'
  WHEN 'Water Station Group' THEN 'COMMUNITY B MEMBERS'
  ELSE cluster_name
END
WHERE cluster_name IN (
  'Market Vendors Cluster',
  'Rice Farmers Cluster',
  'Teachers Cluster',
  'General Membership',
  'Water Station Group'
);

CREATE TABLE IF NOT EXISTS member_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL UNIQUE,
  source_label VARCHAR(160) NOT NULL DEFAULT 'CSV Paste',
  status VARCHAR(40) NOT NULL DEFAULT 'Staged',
  total_rows INTEGER NOT NULL DEFAULT 0,
  ready_rows INTEGER NOT NULL DEFAULT 0,
  issue_rows INTEGER NOT NULL DEFAULT 0,
  created_by VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS finalized_by VARCHAR(80);
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS imported_rows INTEGER NOT NULL DEFAULT 0;
ALTER TABLE member_import_batches ADD COLUMN IF NOT EXISTS skipped_rows INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS member_import_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL,
  row_no INTEGER NOT NULL,
  member_no VARCHAR(40) NOT NULL DEFAULT '',
  full_name VARCHAR(180) NOT NULL DEFAULT '',
  cluster_name VARCHAR(160) NOT NULL DEFAULT '',
  contact_number VARCHAR(60) NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  birthdate DATE,
  civil_status VARCHAR(40) NOT NULL DEFAULT '',
  occupation VARCHAR(120) NOT NULL DEFAULT '',
  membership_date DATE,
  member_status VARCHAR(30) NOT NULL DEFAULT 'Active',
  row_status VARCHAR(40) NOT NULL DEFAULT 'Ready',
  issues TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_member_import_rows_batch FOREIGN KEY (import_no)
    REFERENCES member_import_batches (import_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS opening_balance_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL UNIQUE,
  source_label VARCHAR(160) NOT NULL DEFAULT 'CSV Paste',
  status VARCHAR(40) NOT NULL DEFAULT 'Staged',
  total_rows INTEGER NOT NULL DEFAULT 0,
  ready_rows INTEGER NOT NULL DEFAULT 0,
  issue_rows INTEGER NOT NULL DEFAULT 0,
  total_share_capital NUMERIC(18,2) NOT NULL DEFAULT 0,
  total_savings NUMERIC(18,2) NOT NULL DEFAULT 0,
  created_by VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  finalized_by VARCHAR(80),
  finalized_at TIMESTAMPTZ,
  finalized_rows INTEGER NOT NULL DEFAULT 0,
  skipped_rows INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS opening_balance_import_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_no VARCHAR(40) NOT NULL,
  row_no INTEGER NOT NULL,
  member_no VARCHAR(40) NOT NULL DEFAULT '',
  member_name VARCHAR(180) NOT NULL DEFAULT '',
  share_capital_opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  savings_opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  cutover_date DATE,
  source_reference VARCHAR(120) NOT NULL DEFAULT '',
  row_status VARCHAR(40) NOT NULL DEFAULT 'Ready',
  issues TEXT NOT NULL DEFAULT '[]',
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  finalized_at TIMESTAMPTZ,
  CONSTRAINT fk_opening_balance_import_rows_batch FOREIGN KEY (import_no)
    REFERENCES opening_balance_import_batches (import_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS initial_member_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  share_capital_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  membership_fee_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  savings_deposit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  cash_received NUMERIC(18,2) NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS savings_deposits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deposit_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  cash_received NUMERIC(18,2) NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS share_capital_contributions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contribution_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  cash_received NUMERIC(18,2) NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  received_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS savings_withdrawals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  member_no VARCHAR(40) NOT NULL,
  member_name VARCHAR(180) NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  released_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Teller Batch',
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_no VARCHAR(40) NOT NULL UNIQUE,
  source_type VARCHAR(80) NOT NULL,
  source_no VARCHAR(40) NOT NULL,
  description VARCHAR(220) NOT NULL,
  posted_by VARCHAR(80) NOT NULL,
  posted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_no VARCHAR(40) NOT NULL,
  account_code VARCHAR(40) NOT NULL,
  account_name VARCHAR(160) NOT NULL,
  debit NUMERIC(18,2) NOT NULL DEFAULT 0,
  credit NUMERIC(18,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teller_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no VARCHAR(40) NOT NULL UNIQUE,
  teller_username VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Open',
  opened_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by VARCHAR(80),
  closed_at TIMESTAMPTZ,
  closed_by VARCHAR(80),
  closing_note TEXT,
  expected_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
  actual_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
  variance NUMERIC(18,2) NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  variance_note TEXT,
  variance_noted_by VARCHAR(80),
  variance_noted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS teller_cash_counts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40) NOT NULL,
  expected_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
  actual_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
  variance NUMERIC(18,2) NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  submitted_by VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Submitted',
  submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teller_fundings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funding_no VARCHAR(40) NOT NULL UNIQUE,
  batch_no VARCHAR(40),
  teller_username VARCHAR(80) NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  source_account_code VARCHAR(40) NOT NULL DEFAULT '1020',
  source_account_name VARCHAR(160) NOT NULL DEFAULT 'Cash in Bank',
  reference_no VARCHAR(80) NOT NULL UNIQUE,
  funding_date DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Prepared',
  prepared_by VARCHAR(80) NOT NULL,
  prepared_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  approved_by VARCHAR(80),
  approved_at TIMESTAMPTZ,
  acknowledged_by VARCHAR(80),
  acknowledged_at TIMESTAMPTZ,
  posted_by VARCHAR(80),
  posted_entry_no VARCHAR(40),
  posted_at TIMESTAMPTZ
);

ALTER TABLE teller_fundings ADD COLUMN IF NOT EXISTS posted_by VARCHAR(80);
ALTER TABLE teller_fundings ADD COLUMN IF NOT EXISTS posted_entry_no VARCHAR(40);
ALTER TABLE teller_fundings ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ;

ALTER TABLE members
  ALTER COLUMN share_capital TYPE NUMERIC(18,2) USING share_capital::NUMERIC,
  ALTER COLUMN savings_balance TYPE NUMERIC(18,2) USING savings_balance::NUMERIC,
  ALTER COLUMN previous_loan_balance TYPE NUMERIC(18,2) USING previous_loan_balance::NUMERIC;
ALTER TABLE member_previous_loans
  ALTER COLUMN outstanding_balance TYPE NUMERIC(18,2) USING outstanding_balance::NUMERIC;
ALTER TABLE loan_products
  ADD COLUMN IF NOT EXISTS service_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cbu_rate_bps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cbu_optional BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS insurance_income_account VARCHAR(40) NOT NULL DEFAULT '4050',
  ADD COLUMN IF NOT EXISTS share_capital_account VARCHAR(40) NOT NULL DEFAULT '3010',
  ADD COLUMN IF NOT EXISTS savings_account VARCHAR(40) NOT NULL DEFAULT '2020';
ALTER TABLE loan_products
  ALTER COLUMN minimum_principal TYPE NUMERIC(18,2) USING minimum_principal::NUMERIC,
  ALTER COLUMN maximum_principal TYPE NUMERIC(18,2) USING maximum_principal::NUMERIC,
  ALTER COLUMN processing_fee TYPE NUMERIC(18,2) USING processing_fee::NUMERIC;
ALTER TABLE loan_applications
  ALTER COLUMN requested_principal TYPE NUMERIC(18,2) USING requested_principal::NUMERIC,
  ALTER COLUMN processing_fee TYPE NUMERIC(18,2) USING processing_fee::NUMERIC,
  ALTER COLUMN recommended_principal TYPE NUMERIC(18,2) USING recommended_principal::NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS service_fee_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_fee NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_fee_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cbu_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cbu_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cbu_applied BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS savings_retention_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS savings_retention_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loans
  ALTER COLUMN principal TYPE NUMERIC(18,2) USING principal::NUMERIC,
  ALTER COLUMN processing_fee TYPE NUMERIC(18,2) USING processing_fee::NUMERIC,
  ALTER COLUMN insurance_fee TYPE NUMERIC(18,2) USING insurance_fee::NUMERIC,
  ALTER COLUMN cbu_amount TYPE NUMERIC(18,2) USING cbu_amount::NUMERIC,
  ALTER COLUMN savings_retention_amount TYPE NUMERIC(18,2) USING savings_retention_amount::NUMERIC,
  ALTER COLUMN total_interest TYPE NUMERIC(18,2) USING total_interest::NUMERIC,
  ALTER COLUMN total_payable TYPE NUMERIC(18,2) USING total_payable::NUMERIC,
  ALTER COLUMN net_proceeds TYPE NUMERIC(18,2) USING net_proceeds::NUMERIC;
ALTER TABLE loan_installments
  ALTER COLUMN principal_due TYPE NUMERIC(18,2) USING principal_due::NUMERIC,
  ALTER COLUMN interest_due TYPE NUMERIC(18,2) USING interest_due::NUMERIC,
  ALTER COLUMN total_due TYPE NUMERIC(18,2) USING total_due::NUMERIC;
ALTER TABLE loan_releases
  ADD COLUMN IF NOT EXISTS insurance_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cbu_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS savings_retention_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE loan_releases
  ALTER COLUMN principal TYPE NUMERIC(18,2) USING principal::NUMERIC,
  ALTER COLUMN processing_fee TYPE NUMERIC(18,2) USING processing_fee::NUMERIC,
  ALTER COLUMN insurance_fee TYPE NUMERIC(18,2) USING insurance_fee::NUMERIC,
  ALTER COLUMN cbu_amount TYPE NUMERIC(18,2) USING cbu_amount::NUMERIC,
  ALTER COLUMN savings_retention_amount TYPE NUMERIC(18,2) USING savings_retention_amount::NUMERIC,
  ALTER COLUMN net_proceeds TYPE NUMERIC(18,2) USING net_proceeds::NUMERIC,
  ALTER COLUMN cash_released TYPE NUMERIC(18,2) USING cash_released::NUMERIC;
ALTER TABLE loan_collections
  DROP CONSTRAINT IF EXISTS loan_collections_loan_no_installment_no_key;
ALTER TABLE loan_collections
  ALTER COLUMN principal_amount TYPE NUMERIC(18,2) USING principal_amount::NUMERIC,
  ALTER COLUMN interest_amount TYPE NUMERIC(18,2) USING interest_amount::NUMERIC,
  ALTER COLUMN amount_received TYPE NUMERIC(18,2) USING amount_received::NUMERIC;
ALTER TABLE member_applications
  ALTER COLUMN initial_share_capital TYPE NUMERIC(18,2) USING initial_share_capital::NUMERIC;
ALTER TABLE opening_balance_import_batches
  ALTER COLUMN total_share_capital TYPE NUMERIC(18,2) USING total_share_capital::NUMERIC,
  ALTER COLUMN total_savings TYPE NUMERIC(18,2) USING total_savings::NUMERIC;
ALTER TABLE opening_balance_import_rows
  ALTER COLUMN share_capital_opening_balance TYPE NUMERIC(18,2) USING share_capital_opening_balance::NUMERIC,
  ALTER COLUMN savings_opening_balance TYPE NUMERIC(18,2) USING savings_opening_balance::NUMERIC;
ALTER TABLE initial_member_payments
  ALTER COLUMN share_capital_amount TYPE NUMERIC(18,2) USING share_capital_amount::NUMERIC,
  ALTER COLUMN membership_fee_amount TYPE NUMERIC(18,2) USING membership_fee_amount::NUMERIC,
  ALTER COLUMN savings_deposit_amount TYPE NUMERIC(18,2) USING savings_deposit_amount::NUMERIC,
  ALTER COLUMN cash_received TYPE NUMERIC(18,2) USING cash_received::NUMERIC;
ALTER TABLE savings_deposits
  ALTER COLUMN amount TYPE NUMERIC(18,2) USING amount::NUMERIC,
  ALTER COLUMN cash_received TYPE NUMERIC(18,2) USING cash_received::NUMERIC;
ALTER TABLE share_capital_contributions
  ALTER COLUMN amount TYPE NUMERIC(18,2) USING amount::NUMERIC,
  ALTER COLUMN cash_received TYPE NUMERIC(18,2) USING cash_received::NUMERIC;
ALTER TABLE savings_withdrawals
  ALTER COLUMN amount TYPE NUMERIC(18,2) USING amount::NUMERIC;
ALTER TABLE journal_entry_lines
  ALTER COLUMN debit TYPE NUMERIC(18,2) USING debit::NUMERIC,
  ALTER COLUMN credit TYPE NUMERIC(18,2) USING credit::NUMERIC;
ALTER TABLE teller_batches
  ALTER COLUMN expected_cash TYPE NUMERIC(18,2) USING expected_cash::NUMERIC,
  ALTER COLUMN actual_cash TYPE NUMERIC(18,2) USING actual_cash::NUMERIC,
  ALTER COLUMN variance TYPE NUMERIC(18,2) USING variance::NUMERIC;
ALTER TABLE teller_cash_counts
  ALTER COLUMN expected_cash TYPE NUMERIC(18,2) USING expected_cash::NUMERIC,
  ALTER COLUMN actual_cash TYPE NUMERIC(18,2) USING actual_cash::NUMERIC,
  ALTER COLUMN variance TYPE NUMERIC(18,2) USING variance::NUMERIC;
ALTER TABLE teller_fundings
  ALTER COLUMN amount TYPE NUMERIC(18,2) USING amount::NUMERIC;
