-- Generated from Inventory C-A 2026.xlsx, June 2026 sheet.
-- Item names and duplicate rows are intentionally preserved; quantities and prices are not seeded.

INSERT INTO inventory_categories (category_code, category_name, display_order, status) VALUES
  ('SCHOOL_SUPPLIES', 'School Supplies', 1, 'Active'),
  ('TOILETRIES_MEDICINE', 'Toiletries, Medicine & Napkins', 2, 'Active'),
  ('CANNED_DRINKS', 'Canned Goods, Coffee, Drinks & Milk', 3, 'Active'),
  ('CELLOPHANE_HOUSEHOLD', 'Cellophane, Soap & Household Supplies', 4, 'Active'),
  ('CANDIES_SNACKS', 'Candies & Snacks', 5, 'Active'),
  ('BISCUITS', 'Biscuits', 6, 'Active'),
  ('KITCHEN_CONDIMENTS', 'Kitchen Supplies & Condiments', 7, 'Active')
ON CONFLICT (category_code) DO UPDATE SET category_name = EXCLUDED.category_name, display_order = EXCLUDED.display_order, status = 'Active';

INSERT INTO inventory_items (item_code, item_name, status, created_by, updated_by) VALUES
  ('CAN-0001', 'Ballpen- Flex Stick 12''s .5 (box to pcs)', 'Active', 'system', 'system'),
  ('CAN-0002', 'ballpen-flex stick pcs', 'Active', 'system', 'system'),
  ('CAN-0003', 'Ballpen-Flex Stick Neo Box', 'Active', 'system', 'system'),
  ('CAN-0004', 'Bondpaper-Paper One L rm', 'Active', 'system', 'system'),
  ('CAN-0005', 'bondpaper-Paper One L pcs', 'Active', 'system', 'system'),
  ('CAN-0006', 'Bondpaper-Copy One Short rm', 'Active', 'system', 'system'),
  ('CAN-0007', 'bondpaper-copy one short pcs', 'Active', 'system', 'system'),
  ('CAN-0008', 'Bondpaper- A4 rm', 'Active', 'system', 'system'),
  ('CAN-0009', 'bondpaper-A4 pcs', 'Active', 'system', 'system'),
  ('CAN-0010', 'Oslo paper pcs', 'Active', 'system', 'system'),
  ('CAN-0011', 'Brown envelope Long', 'Active', 'system', 'system'),
  ('CAN-0012', 'Brown envelope Short', 'Active', 'system', 'system'),
  ('CAN-0013', 'Chalk-white joy', 'Active', 'system', 'system'),
  ('CAN-0014', 'Chalk-Virgo pcs', 'Active', 'system', 'system'),
  ('CAN-0015', 'Cartolina Nipis', 'Active', 'system', 'system'),
  ('CAN-0016', 'Cartolina Baga', 'Active', 'system', 'system'),
  ('CAN-0017', 'Crayola', 'Active', 'system', 'system'),
  ('CAN-0018', 'Super tape', 'Active', 'system', 'system'),
  ('CAN-0019', 'Correction Paper Tape', 'Active', 'system', 'system'),
  ('CAN-0020', 'Correction Paper Tape Dominic big', 'Active', 'system', 'system'),
  ('CAN-0021', 'Dressmaker Pins pad', 'Active', 'system', 'system'),
  ('CAN-0022', 'Double Sided Tape', 'Active', 'system', 'system'),
  ('CAN-0023', 'Envelope L (White)', 'Active', 'system', 'system'),
  ('CAN-0024', 'Envelope S (White)', 'Active', 'system', 'system'),
  ('CAN-0025', 'Envelope Plastic Long', 'Active', 'system', 'system'),
  ('CAN-0026', 'Texas 3x10 pcs', 'Active', 'system', 'system'),
  ('CAN-0027', 'Texas 3x16 pcks', 'Active', 'system', 'system'),
  ('CAN-0028', 'fastener pcs', 'Active', 'system', 'system'),
  ('CAN-0029', 'Flex Office Marker (pcs)', 'Active', 'system', 'system'),
  ('CAN-0030', 'Flex Office Marker Box', 'Active', 'system', 'system'),
  ('CAN-0031', 'Folder Brown Long pcs', 'Active', 'system', 'system'),
  ('CAN-0032', 'Folder Brown short pcs', 'Active', 'system', 'system'),
  ('CAN-0033', 'floor wax', 'Active', 'system', 'system'),
  ('CAN-0034', 'Folder White Long pcs', 'Active', 'system', 'system'),
  ('CAN-0035', 'Plastic Folder Cover Long', 'Active', 'system', 'system'),
  ('CAN-0036', 'Plastic Envelope Short', 'Active', 'system', 'system'),
  ('CAN-0037', 'Plastic Envelope Long', 'Active', 'system', 'system'),
  ('CAN-0038', 'Envelope Brown', 'Active', 'system', 'system'),
  ('CAN-0039', 'Sliding Folder Long pcs', 'Active', 'system', 'system'),
  ('CAN-0040', 'Graphing Paper pcs', 'Active', 'system', 'system'),
  ('CAN-0041', 'Graphing paper RM', 'Active', 'system', 'system'),
  ('CAN-0042', 'Index Card Fortune Rm', 'Active', 'system', 'system'),
  ('CAN-0043', 'Index Card Fortune Ad 5x8 pcs', 'Active', 'system', 'system'),
  ('CAN-0044', 'Intermediate paper (Fold)pcs.', 'Active', 'system', 'system'),
  ('CAN-0045', 'Intermediate Paper ream to pad', 'Active', 'system', 'system'),
  ('CAN-0046', 'Illustration board 1/4', 'Active', 'system', 'system'),
  ('CAN-0047', 'Illustration board 1/8', 'Active', 'system', 'system'),
  ('CAN-0048', 'Mygel Sign Pen', 'Active', 'system', 'system'),
  ('CAN-0049', 'Mygel Sign Pen Pcs', 'Active', 'system', 'system'),
  ('CAN-0050', 'Manila Paper GMC pcs', 'Active', 'system', 'system'),
  ('CAN-0051', 'Mongol 2', 'Active', 'system', 'system'),
  ('CAN-0052', 'Mongol 2 Pcs', 'Active', 'system', 'system'),
  ('CAN-0053', 'Neon Paper L 250''s', 'Active', 'system', 'system'),
  ('CAN-0054', 'Neon Paper L 250''s (pcks to pcs)', 'Active', 'system', 'system'),
  ('CAN-0055', 'Notebook pcs', 'Active', 'system', 'system'),
  ('CAN-0056', 'Notebook w/ yarn University 40L', 'Active', 'system', 'system'),
  ('CAN-0057', 'Notebook w/ yarn University 80L pcs B.N', 'Active', 'system', 'system'),
  ('CAN-0058', 'Plastic Envelope Long', 'Active', 'system', 'system'),
  ('CAN-0059', 'Plastic Envelope Short', 'Active', 'system', 'system'),
  ('CAN-0060', 'Packaging tape', 'Active', 'system', 'system'),
  ('CAN-0061', 'Paper Clips x Boxes', 'Active', 'system', 'system'),
  ('CAN-0062', 'Color paper Rm', 'Active', 'system', 'system'),
  ('CAN-0063', 'color paper', 'Active', 'system', 'system'),
  ('CAN-0064', 'Paper Clips pcs', 'Active', 'system', 'system'),
  ('CAN-0065', 'Pencil Mongol 2 bx', 'Active', 'system', 'system'),
  ('CAN-0066', 'Pilot Marker (Broad)', 'Active', 'system', 'system'),
  ('CAN-0067', 'Pilot Marker ( fine )', 'Active', 'system', 'system'),
  ('CAN-0068', 'Pilot Marker ( Broad )', 'Active', 'system', 'system'),
  ('CAN-0069', 'Pilot-Refill ink', 'Active', 'system', 'system'),
  ('CAN-0070', 'Marker', 'Active', 'system', 'system'),
  ('CAN-0071', 'Ruler', 'Active', 'system', 'system'),
  ('CAN-0072', 'Plastic Ruler', 'Active', 'system', 'system'),
  ('CAN-0073', 'Protractor (big) pcs', 'Active', 'system', 'system'),
  ('CAN-0074', 'Rabbit Eraser TM 320 (small)', 'Active', 'system', 'system'),
  ('CAN-0075', 'Rabbit Eraser TM 321(big)', 'Active', 'system', 'system'),
  ('CAN-0076', 'Scissors B', 'Active', 'system', 'system'),
  ('CAN-0077', 'Scissors S', 'Active', 'system', 'system'),
  ('CAN-0078', 'Scotch Tape armak', 'Active', 'system', 'system'),
  ('CAN-0079', 'Scotch Tape 1'''' thick 240''s', 'Active', 'system', 'system'),
  ('CAN-0080', 'Scotch tape Armak', 'Active', 'system', 'system'),
  ('CAN-0081', 'Scotch tape Armak', 'Active', 'system', 'system'),
  ('CAN-0082', 'Scotch tape pc 25''s/pad', 'Active', 'system', 'system'),
  ('CAN-0083', 'Staple wire #10 20''s/box', 'Active', 'system', 'system'),
  ('CAN-0084', 'Staples No.10 box', 'Active', 'system', 'system'),
  ('CAN-0085', 'Staple no.35-5m box', 'Active', 'system', 'system'),
  ('CAN-0086', 'Staple no.35 box', 'Active', 'system', 'system'),
  ('CAN-0087', 'Staple wire #35 gmc bx', 'Active', 'system', 'system'),
  ('CAN-0088', 'Staple wire #35 gmc pcs', 'Active', 'system', 'system'),
  ('CAN-0089', 'Stationary Tape pcs', 'Active', 'system', 'system'),
  ('CAN-0090', 'Sharpener', 'Active', 'system', 'system'),
  ('CAN-0091', 'Thumbtacks Mitsuya 24''s/box', 'Active', 'system', 'system'),
  ('CAN-0092', 'Yarn', 'Active', 'system', 'system'),
  ('CAN-0093', 'Yellow Paper (cs to rm to pads)', 'Active', 'system', 'system'),
  ('CAN-0094', 'Yellow Paper( Folds)pcs.', 'Active', 'system', 'system'),
  ('CAN-0095', 'MASKING TAPE PCS.', 'Active', 'system', 'system'),
  ('CAN-0096', 'Elmers glue 130g', 'Active', 'system', 'system'),
  ('CAN-0097', 'Pot holder pcs', 'Active', 'system', 'system'),
  ('CAN-0098', 'Twin lion bgs', 'Active', 'system', 'system'),
  ('CAN-0099', 'Elmers glue 40g', 'Active', 'system', 'system'),
  ('CAN-0100', 'Amoxicillin', 'Active', 'system', 'system'),
  ('CAN-0101', 'Baygon Catol', 'Active', 'system', 'system'),
  ('CAN-0102', 'Band Aid', 'Active', 'system', 'system'),
  ('CAN-0103', 'Bioflue', 'Active', 'system', 'system'),
  ('CAN-0104', 'Biogesic', 'Active', 'system', 'system'),
  ('CAN-0105', 'Casino Alcohol 150ml', 'Active', 'system', 'system'),
  ('CAN-0106', 'charmee pcks', 'Active', 'system', 'system'),
  ('CAN-0107', 'Charmee Panty Liner Violet 8''s', 'Active', 'system', 'system'),
  ('CAN-0108', 'Charmee Panty Liner Pink 8''s', 'Active', 'system', 'system'),
  ('CAN-0109', 'Charmee pads', 'Active', 'system', 'system'),
  ('CAN-0110', 'Emi match', 'Active', 'system', 'system'),
  ('CAN-0111', 'Ethyl Alcohol 160ml', 'Active', 'system', 'system'),
  ('CAN-0112', 'Ethyl Alcohol 60ml', 'Active', 'system', 'system'),
  ('CAN-0113', 'Grisp Gel', 'Active', 'system', 'system'),
  ('CAN-0114', 'Gillette', 'Active', 'system', 'system'),
  ('CAN-0115', 'Femme Tissue', 'Active', 'system', 'system'),
  ('CAN-0116', 'Purity Cotton', 'Active', 'system', 'system'),
  ('CAN-0117', 'Kami Tissue', 'Active', 'system', 'system'),
  ('CAN-0118', 'Jade Tissue Rolls', 'Active', 'system', 'system'),
  ('CAN-0119', 'Johnson Baby Powder', 'Active', 'system', 'system'),
  ('CAN-0120', 'Lion Tiger', 'Active', 'system', 'system'),
  ('CAN-0121', 'MEFENAMIC acid pcs', 'Active', 'system', 'system'),
  ('CAN-0122', 'Modess All night pcs', 'Active', 'system', 'system'),
  ('CAN-0123', 'Modess All night pack', 'Active', 'system', 'system'),
  ('CAN-0124', 'Modess Reg. Wings', 'Active', 'system', 'system'),
  ('CAN-0125', 'Modess Reg.', 'Active', 'system', 'system'),
  ('CAN-0126', 'hair gel', 'Active', 'system', 'system'),
  ('CAN-0127', 'Modess Reg.', 'Active', 'system', 'system'),
  ('CAN-0128', 'Rexona (men)', 'Active', 'system', 'system'),
  ('CAN-0129', 'Rexona (women)', 'Active', 'system', 'system'),
  ('CAN-0130', 'Lotus Toothbrush', 'Active', 'system', 'system'),
  ('CAN-0131', 'Sanicare C- Wipes 35''s', 'Active', 'system', 'system'),
  ('CAN-0132', 'Sanicare C- Wipes 55''s', 'Active', 'system', 'system'),
  ('CAN-0133', 'Sanicare B-Wipes 15''s', 'Active', 'system', 'system'),
  ('CAN-0134', 'Sisters Napkin', 'Active', 'system', 'system'),
  ('CAN-0135', 'Tisyu Handy Pack', 'Active', 'system', 'system'),
  ('CAN-0136', 'Hand gloves bx', 'Active', 'system', 'system'),
  ('CAN-0137', 'Hand gloves pcs', 'Active', 'system', 'system'),
  ('CAN-0138', 'Venus Tawas', 'Active', 'system', 'system'),
  ('CAN-0139', 'Argentina Corned Beef', 'Active', 'system', 'system'),
  ('CAN-0140', 'BearBrand Swak tie to pcs', 'Active', 'system', 'system'),
  ('CAN-0141', 'Bear Brand Choco tie to pcs', 'Active', 'system', 'system'),
  ('CAN-0142', 'Birch tree tie', 'Active', 'system', 'system'),
  ('CAN-0143', 'birch tree pcs.', 'Active', 'system', 'system'),
  ('CAN-0144', 'Century Tuna Flakes & Oil', 'Active', 'system', 'system'),
  ('CAN-0145', 'C2 Solo', 'Active', 'system', 'system'),
  ('CAN-0146', 'C2 Solo Cs.', 'Active', 'system', 'system'),
  ('CAN-0147', 'Chocolait 200ml', 'Active', 'system', 'system'),
  ('CAN-0148', 'Chocolait 250ml', 'Active', 'system', 'system'),
  ('CAN-0149', 'Chocolait 110ml', 'Active', 'system', 'system'),
  ('CAN-0150', 'Chuckie 6''s', 'Active', 'system', 'system'),
  ('CAN-0151', 'Coke Swakto CS', 'Active', 'system', 'system'),
  ('CAN-0152', 'Coke Swakto pcs', 'Active', 'system', 'system'),
  ('CAN-0153', 'Coke/Sprite/Royal 1.25 (6''s) pcs', 'Active', 'system', 'system'),
  ('CAN-0154', 'Coke/Sprite/Royal 1.5 (12''s)', 'Active', 'system', 'system'),
  ('CAN-0155', 'Coke/Sprite/Royal 1.5 (12''s)Cs', 'Active', 'system', 'system'),
  ('CAN-0156', 'Coke/Sprite/Royal Mismo 12''s Pcs', 'Active', 'system', 'system'),
  ('CAN-0157', 'cup noodles', 'Active', 'system', 'system'),
  ('CAN-0158', 'Close up TP', 'Active', 'system', 'system'),
  ('CAN-0159', 'Daisy Condense Milk', 'Active', 'system', 'system'),
  ('CAN-0160', 'DM- ACE 6''s pcs', 'Active', 'system', 'system'),
  ('CAN-0161', 'DM- 4 SEASONS Fiber 6''s pcs', 'Active', 'system', 'system'),
  ('CAN-0162', 'DM- 4 SEASONS Sweetend 6''s pcs', 'Active', 'system', 'system'),
  ('CAN-0163', 'DM- 4 SEASONS Heart Smart 6''s pcs', 'Active', 'system', 'system'),
  ('CAN-0164', 'Dutchmill 4''s 90ml', 'Active', 'system', 'system'),
  ('CAN-0165', 'Dutchmill 4''s 110ml', 'Active', 'system', 'system'),
  ('CAN-0166', 'Dutchmil small pcks', 'Active', 'system', 'system'),
  ('CAN-0167', 'Dutchmil big pcks', 'Active', 'system', 'system'),
  ('CAN-0168', 'Dutchmill 4''s 180ml', 'Active', 'system', 'system'),
  ('CAN-0169', 'Energen Champion', 'Active', 'system', 'system'),
  ('CAN-0170', 'Fit''nRight (doz to bot)330ml', 'Active', 'system', 'system'),
  ('CAN-0171', 'nissin spicy beef small', 'Active', 'system', 'system'),
  ('CAN-0172', 'nissin sotanghon small', 'Active', 'system', 'system'),
  ('CAN-0173', 'Nissin spicy pork tonkotso small', 'Active', 'system', 'system'),
  ('CAN-0174', 'Nissin Cup Noodles Tankotsu', 'Active', 'system', 'system'),
  ('CAN-0175', 'Nissin Cup Noodles Cheezy Seafood', 'Active', 'system', 'system'),
  ('CAN-0176', 'Nissin Cup Noodles Hot Cheezy 45g', 'Active', 'system', 'system'),
  ('CAN-0177', 'Nissin Cup Noodles Creamy Seafood 45g', 'Active', 'system', 'system'),
  ('CAN-0178', 'Nissin Cup Noodles Nissin Batchoy 45g', 'Active', 'system', 'system'),
  ('CAN-0179', 'LM Batchoy Big', 'Active', 'system', 'system'),
  ('CAN-0180', 'L-Me Cup Noodles Batchoy /Bulalo/Chicken40g', 'Active', 'system', 'system'),
  ('CAN-0181', 'L-Me Cup Noodles Sutanghon Seafood', 'Active', 'system', 'system'),
  ('CAN-0182', 'LM Batchoy small', 'Active', 'system', 'system'),
  ('CAN-0183', 'LM Chicken small', 'Active', 'system', 'system'),
  ('CAN-0184', 'L-Me Cup Noodles Sutanghon', 'Active', 'system', 'system'),
  ('CAN-0185', 'L-M Cup Go Cup', 'Active', 'system', 'system'),
  ('CAN-0186', 'LM spicy bulalo', 'Active', 'system', 'system'),
  ('CAN-0187', 'L-Me Cup Noodles Jampong', 'Active', 'system', 'system'),
  ('CAN-0188', 'L-Me Cup Noodles SeaFoods', 'Active', 'system', 'system'),
  ('CAN-0189', 'L-Me Cup Noodles Spicy Batchoy', 'Active', 'system', 'system'),
  ('CAN-0190', 'L-Me Cup Noodles Seafood/Shrimp', 'Active', 'system', 'system'),
  ('CAN-0191', 'L-Me Chicken', 'Active', 'system', 'system'),
  ('CAN-0192', 'Lm- Noodles Jampong 70g', 'Active', 'system', 'system'),
  ('CAN-0193', 'L-M Pancit Cantoon Kasalo', 'Active', 'system', 'system'),
  ('CAN-0194', 'L-ME P cantoon 60g', 'Active', 'system', 'system'),
  ('CAN-0195', 'L-ME Pancit Cantoon Hot Chilli', 'Active', 'system', 'system'),
  ('CAN-0196', 'L-ME jampong noodles', 'Active', 'system', 'system'),
  ('CAN-0197', 'Holiday Carne Norte 150g', 'Active', 'system', 'system'),
  ('CAN-0198', 'Holiday Beef Loaf 150g', 'Active', 'system', 'system'),
  ('CAN-0199', 'Holiday Beef Loaf 215g', 'Active', 'system', 'system'),
  ('CAN-0200', 'Holiday Corned Beef 150g', 'Active', 'system', 'system'),
  ('CAN-0201', 'Holiday Pork & Beans', 'Active', 'system', 'system'),
  ('CAN-0202', 'Nestea Apple Doz.', 'Active', 'system', 'system'),
  ('CAN-0203', 'Nestea pcks', 'Active', 'system', 'system'),
  ('CAN-0204', 'Budget pack', 'Active', 'system', 'system'),
  ('CAN-0205', 'Nestea Apple Pcs', 'Active', 'system', 'system'),
  ('CAN-0206', 'Juice Tang (sachet)', 'Active', 'system', 'system'),
  ('CAN-0207', 'Great Taste stick Pack', 'Active', 'system', 'system'),
  ('CAN-0208', 'Great Taste stick Pcs', 'Active', 'system', 'system'),
  ('CAN-0209', 'Great Taste White TP', 'Active', 'system', 'system'),
  ('CAN-0210', 'Kopiko Black TP pcs', 'Active', 'system', 'system'),
  ('CAN-0211', 'Kopiko Black Bag', 'Active', 'system', 'system'),
  ('CAN-0212', 'Kopiko Brown TP', 'Active', 'system', 'system'),
  ('CAN-0213', 'Kopiko Brown Pcs', 'Active', 'system', 'system'),
  ('CAN-0214', 'Kopiko Blanca TP Tie', 'Active', 'system', 'system'),
  ('CAN-0215', 'Kopiko Blanca Single', 'Active', 'system', 'system'),
  ('CAN-0216', 'Mafran Catesup 190 gm', 'Active', 'system', 'system'),
  ('CAN-0217', 'Mang Tomas 40g', 'Active', 'system', 'system'),
  ('CAN-0218', 'Mega Sardines Green', 'Active', 'system', 'system'),
  ('CAN-0219', 'Mega Sardines Red pcs', 'Active', 'system', 'system'),
  ('CAN-0220', 'Mega Sardines Red Pack', 'Active', 'system', 'system'),
  ('CAN-0221', 'Milo DZ', 'Active', 'system', 'system'),
  ('CAN-0222', 'Milo RTD 4''s 180ml', 'Active', 'system', 'system'),
  ('CAN-0223', 'Milo Tp 24g', 'Active', 'system', 'system'),
  ('CAN-0224', 'Nescafe Original S', 'Active', 'system', 'system'),
  ('CAN-0225', 'Nescafe Creamy White Single', 'Active', 'system', 'system'),
  ('CAN-0226', 'Nescafe Creamy White TP', 'Active', 'system', 'system'),
  ('CAN-0227', 'Nescafe stick Bag', 'Active', 'system', 'system'),
  ('CAN-0228', 'Nescafe stick pcs', 'Active', 'system', 'system'),
  ('CAN-0229', 'PEPSI /Mountain Dew 290ml Cs.', 'Active', 'system', 'system'),
  ('CAN-0230', 'SAN MARINO Tuna flakes', 'Active', 'system', 'system'),
  ('CAN-0231', 'SAN MARINO Corned Tuna 150g', 'Active', 'system', 'system'),
  ('CAN-0232', 'SAN MARINO Corned Tuna 85g', 'Active', 'system', 'system'),
  ('CAN-0233', 'SAN MARINO Chilli - Corned Tuna 85g', 'Active', 'system', 'system'),
  ('CAN-0234', 'TANG JUICE', 'Active', 'system', 'system'),
  ('CAN-0235', 'ZEST-O pcs', 'Active', 'system', 'system'),
  ('CAN-0236', 'Wow Ulam', 'Active', 'system', 'system'),
  ('CAN-0237', 'VETSIN 250g', 'Active', 'system', 'system'),
  ('CAN-0238', 'VETSIN pck 11g', 'Active', 'system', 'system'),
  ('CAN-0239', 'Yakult 1cs(10pck-5pcs)', 'Active', 'system', 'system'),
  ('CAN-0240', 'Yakult 1cs(10pck)', 'Active', 'system', 'system'),
  ('CAN-0241', 'UFC Catesup', 'Active', 'system', 'system'),
  ('CAN-0242', 'MAGIC SARAP TP', 'Active', 'system', 'system'),
  ('CAN-0243', 'MAGIC SARAP', 'Active', 'system', 'system'),
  ('CAN-0244', 'Golden Bihon pcks', 'Active', 'system', 'system'),
  ('CAN-0245', 'GOLDEN BIHON Sack', 'Active', 'system', 'system'),
  ('CAN-0246', 'SUKI BIHON PCS', 'Active', 'system', 'system'),
  ('CAN-0247', 'Cellophane Cutty Sark 6x12', 'Active', 'system', 'system'),
  ('CAN-0248', 'Cellophane Cutty Sark 5x10 rm', 'Active', 'system', 'system'),
  ('CAN-0249', 'Cellophane- Blue Whale', 'Active', 'system', 'system'),
  ('CAN-0250', 'Cellophane- Oxo Plus', 'Active', 'system', 'system'),
  ('CAN-0251', 'Cellophane- Torino 3x10 PCS', 'Active', 'system', 'system'),
  ('CAN-0252', 'Cheers Bag', 'Active', 'system', 'system'),
  ('CAN-0253', 'Cheers Bag', 'Active', 'system', 'system'),
  ('CAN-0254', 'Cheers Bag', 'Active', 'system', 'system'),
  ('CAN-0255', 'Disposable Pop-I Fork 25''s', 'Active', 'system', 'system'),
  ('CAN-0256', 'Cheers Spoon &fork pcs', 'Active', 'system', 'system'),
  ('CAN-0257', 'Cheers Spoon &fork pcK', 'Active', 'system', 'system'),
  ('CAN-0258', 'Disposable Glass 6''oz. Party Cups', 'Active', 'system', 'system'),
  ('CAN-0259', 'Disposable Glass 7''oz. Party Cups', 'Active', 'system', 'system'),
  ('CAN-0260', 'Downey Fabcon', 'Active', 'system', 'system'),
  ('CAN-0261', 'Efficascent oil 25 ml', 'Active', 'system', 'system'),
  ('CAN-0262', 'efficascent oil e-strenght 25ml', 'Active', 'system', 'system'),
  ('CAN-0263', 'Efficascent Extreme Bot. 25ml', 'Active', 'system', 'system'),
  ('CAN-0264', 'Wings Powder pcs', 'Active', 'system', 'system'),
  ('CAN-0265', 'Safeguard 22g', 'Active', 'system', 'system'),
  ('CAN-0266', 'Bioderm', 'Active', 'system', 'system'),
  ('CAN-0267', 'Styroware 8''oz pcs', 'Active', 'system', 'system'),
  ('CAN-0268', 'Styroware 8''oz pack', 'Active', 'system', 'system'),
  ('CAN-0269', 'StarWax Dye 90g', 'Active', 'system', 'system'),
  ('CAN-0270', 'Surf Powder', 'Active', 'system', 'system'),
  ('CAN-0271', 'Bareta Bar', 'Active', 'system', 'system'),
  ('CAN-0272', 'Zonrox 1L', 'Active', 'system', 'system'),
  ('CAN-0273', 'Paper Plate Pck', 'Active', 'system', 'system'),
  ('CAN-0274', 'Paper Plate pcs', 'Active', 'system', 'system'),
  ('CAN-0275', 'Microwavable 5''s', 'Active', 'system', 'system'),
  ('CAN-0276', 'Microwavable 10''s', 'Active', 'system', 'system'),
  ('CAN-0277', 'Criss cross', 'Active', 'system', 'system'),
  ('CAN-0278', 'Chezzy Spicy Big', 'Active', 'system', 'system'),
  ('CAN-0279', 'Cheezy Asstd pcs', 'Active', 'system', 'system'),
  ('CAN-0280', 'Cheezy 70g', 'Active', 'system', 'system'),
  ('CAN-0281', 'Chezzy 70g Spicy', 'Active', 'system', 'system'),
  ('CAN-0282', 'Chiz Curls', 'Active', 'system', 'system'),
  ('CAN-0283', 'Chiz Curls Big', 'Active', 'system', 'system'),
  ('CAN-0284', 'Chippy Big 108g(Bue/Red)', 'Active', 'system', 'system'),
  ('CAN-0285', 'Chippy Big 108g Green Big', 'Active', 'system', 'system'),
  ('CAN-0286', 'Chippy Red', 'Active', 'system', 'system'),
  ('CAN-0287', 'Chippy Green', 'Active', 'system', 'system'),
  ('CAN-0288', 'Chippy Corn Tube', 'Active', 'system', 'system'),
  ('CAN-0289', 'Clover Chilly SM', 'Active', 'system', 'system'),
  ('CAN-0290', 'Corn Bits Orig pcs', 'Active', 'system', 'system'),
  ('CAN-0291', 'Corn Bits Orig BAGS', 'Active', 'system', 'system'),
  ('CAN-0292', 'Cornbits Special Bags', 'Active', 'system', 'system'),
  ('CAN-0293', 'Cracklings', 'Active', 'system', 'system'),
  ('CAN-0294', 'Cracklings Spicy', 'Active', 'system', 'system'),
  ('CAN-0295', 'Flat Tops 100 pck', 'Active', 'system', 'system'),
  ('CAN-0296', 'Flat Tops 100 pcs.', 'Active', 'system', 'system'),
  ('CAN-0297', 'Dingdong Mix Nuts 30g', 'Active', 'system', 'system'),
  ('CAN-0298', 'Dingdong Mix Nuts 100g pcs', 'Active', 'system', 'system'),
  ('CAN-0299', 'Freshmint Jar to pcs', 'Active', 'system', 'system'),
  ('CAN-0300', 'Freshmint Jar', 'Active', 'system', 'system'),
  ('CAN-0301', 'Happy Peanut Red/Blue', 'Active', 'system', 'system'),
  ('CAN-0302', 'Happy Peanut White 100g', 'Active', 'system', 'system'),
  ('CAN-0303', 'Happy SM', 'Active', 'system', 'system'),
  ('CAN-0304', 'Hi-Ho', 'Active', 'system', 'system'),
  ('CAN-0305', 'Happy Red', 'Active', 'system', 'system'),
  ('CAN-0306', 'Hi-Ho', 'Active', 'system', 'system'),
  ('CAN-0307', 'I-Cool bag', 'Active', 'system', 'system'),
  ('CAN-0308', 'I-Cool pcs', 'Active', 'system', 'system'),
  ('CAN-0309', 'Jelly Candy', 'Active', 'system', 'system'),
  ('CAN-0310', 'Judge Pck', 'Active', 'system', 'system'),
  ('CAN-0311', 'Kindymint 100''s', 'Active', 'system', 'system'),
  ('CAN-0312', 'Kindymint bg 50''s', 'Active', 'system', 'system'),
  ('CAN-0313', 'Kindymint pcs', 'Active', 'system', 'system'),
  ('CAN-0314', 'Lipps pop stick 60''s pck', 'Active', 'system', 'system'),
  ('CAN-0315', 'Lipps pop stick 20''s pck', 'Active', 'system', 'system'),
  ('CAN-0316', 'Lipps pcs', 'Active', 'system', 'system'),
  ('CAN-0317', 'Lion', 'Active', 'system', 'system'),
  ('CAN-0318', 'Love Lips', 'Active', 'system', 'system'),
  ('CAN-0319', 'Mang Juan sm', 'Active', 'system', 'system'),
  ('CAN-0320', 'Martys 26g', 'Active', 'system', 'system'),
  ('CAN-0321', 'Maxx pcs', 'Active', 'system', 'system'),
  ('CAN-0322', 'Maxx pck 50pcs', 'Active', 'system', 'system'),
  ('CAN-0323', 'Mealbox', 'Active', 'system', 'system'),
  ('CAN-0324', 'Mentos Mini roll bags', 'Active', 'system', 'system'),
  ('CAN-0325', 'Mentos Mini roll pcs', 'Active', 'system', 'system'),
  ('CAN-0326', 'Muncher', 'Active', 'system', 'system'),
  ('CAN-0327', 'Mr Chips big pcs', 'Active', 'system', 'system'),
  ('CAN-0328', 'Mr. Chips', 'Active', 'system', 'system'),
  ('CAN-0329', 'Potato Chips Big pcs', 'Active', 'system', 'system'),
  ('CAN-0330', 'Nova Fun Size', 'Active', 'system', 'system'),
  ('CAN-0331', 'Nova SM', 'Active', 'system', 'system'),
  ('CAN-0332', 'Nova Big', 'Active', 'system', 'system'),
  ('CAN-0333', 'PIC- A Big/Piatos', 'Active', 'system', 'system'),
  ('CAN-0334', 'Roller Coaster', 'Active', 'system', 'system'),
  ('CAN-0335', 'Roller Coaster Big', 'Active', 'system', 'system'),
  ('CAN-0336', 'Onion Ring 24g', 'Active', 'system', 'system'),
  ('CAN-0337', 'Piatos Big', 'Active', 'system', 'system'),
  ('CAN-0338', 'Piatos', 'Active', 'system', 'system'),
  ('CAN-0339', 'Piatos Funsize Cs', 'Active', 'system', 'system'),
  ('CAN-0340', 'Piatos SM', 'Active', 'system', 'system'),
  ('CAN-0341', 'Pier 28', 'Active', 'system', 'system'),
  ('CAN-0342', 'Oishi Asstd', 'Active', 'system', 'system'),
  ('CAN-0343', 'OISHi Prawn crackers', 'Active', 'system', 'system'),
  ('CAN-0344', 'OISHi Fish Cracker', 'Active', 'system', 'system'),
  ('CAN-0345', 'Oishe Crackling', 'Active', 'system', 'system'),
  ('CAN-0346', 'Snowbear pck 100''s', 'Active', 'system', 'system'),
  ('CAN-0347', 'Snowbear pcs', 'Active', 'system', 'system'),
  ('CAN-0348', 'Super Crunch', 'Active', 'system', 'system'),
  ('CAN-0349', 'Tattos bgs', 'Active', 'system', 'system'),
  ('CAN-0350', 'Tattos asst. 60g', 'Active', 'system', 'system'),
  ('CAN-0351', 'Tattos asst. 58g', 'Active', 'system', 'system'),
  ('CAN-0352', 'Tostas SM', 'Active', 'system', 'system'),
  ('CAN-0353', 'V-Cut SM', 'Active', 'system', 'system'),
  ('CAN-0354', 'V-Cut Big', 'Active', 'system', 'system'),
  ('CAN-0355', 'X.O 50''s PCk', 'Active', 'system', 'system'),
  ('CAN-0356', 'X.O 50''s PCS.', 'Active', 'system', 'system'),
  ('CAN-0357', 'Bingo 10''s pcs.', 'Active', 'system', 'system'),
  ('CAN-0358', 'Bengbeng Box', 'Active', 'system', 'system'),
  ('CAN-0359', 'Bengbeng Pcs', 'Active', 'system', 'system'),
  ('CAN-0360', 'Bravo bgs', 'Active', 'system', 'system'),
  ('CAN-0361', 'Butter Coconut Slug', 'Active', 'system', 'system'),
  ('CAN-0362', 'Cal- Cheeze', 'Active', 'system', 'system'),
  ('CAN-0363', 'Choco mucho Minis 20''s bag', 'Active', 'system', 'system'),
  ('CAN-0364', 'Choco mucho Minis 40''s bag', 'Active', 'system', 'system'),
  ('CAN-0365', 'Choco mucho Minis pcs', 'Active', 'system', 'system'),
  ('CAN-0366', 'Choco Mucho Cookie pcs', 'Active', 'system', 'system'),
  ('CAN-0367', 'Choco Mucho Cookie Bag', 'Active', 'system', 'system'),
  ('CAN-0368', 'Choco Mucho box', 'Active', 'system', 'system'),
  ('CAN-0369', 'Choco Mucho Yellow', 'Active', 'system', 'system'),
  ('CAN-0370', 'Choco Mucho box', 'Active', 'system', 'system'),
  ('CAN-0371', 'Choco Mucho Bar pcs', 'Active', 'system', 'system'),
  ('CAN-0372', 'Cloud 9 Overload Bar Box to pcs', 'Active', 'system', 'system'),
  ('CAN-0373', 'Cloud 9 Overload Box', 'Active', 'system', 'system'),
  ('CAN-0374', 'Cheese Ring S', 'Active', 'system', 'system'),
  ('CAN-0375', 'Cal Cheese pcs', 'Active', 'system', 'system'),
  ('CAN-0376', 'Cloud 9 Classic Box', 'Active', 'system', 'system'),
  ('CAN-0377', 'Cloud 9 Classic pcs', 'Active', 'system', 'system'),
  ('CAN-0378', 'Crean -O Crinkles bags', 'Active', 'system', 'system'),
  ('CAN-0379', 'Crean -O Crinkles pcs', 'Active', 'system', 'system'),
  ('CAN-0380', 'chocolate saver pcs', 'Active', 'system', 'system'),
  ('CAN-0381', 'chocolate worms pcs', 'Active', 'system', 'system'),
  ('CAN-0382', 'chocolate savor pcs', 'Active', 'system', 'system'),
  ('CAN-0383', 'Crean -O Chocolate Chips Pck', 'Active', 'system', 'system'),
  ('CAN-0384', 'Crean -O chocolate COOKIES pcs', 'Active', 'system', 'system'),
  ('CAN-0385', 'Crean -O chocolate BAG', 'Active', 'system', 'system'),
  ('CAN-0386', 'Crean -O Cream', 'Active', 'system', 'system'),
  ('CAN-0387', 'Dewberry Cheeze bag', 'Active', 'system', 'system'),
  ('CAN-0388', 'Dewberry Cheeze pcs', 'Active', 'system', 'system'),
  ('CAN-0389', 'Doowee Bag', 'Active', 'system', 'system'),
  ('CAN-0390', 'Doowee pcs', 'Active', 'system', 'system'),
  ('CAN-0391', 'Eggnog', 'Active', 'system', 'system'),
  ('CAN-0392', 'Fita Bis, Bag 15s', 'Active', 'system', 'system'),
  ('CAN-0393', 'Fita Cracker promo', 'Active', 'system', 'system'),
  ('CAN-0394', 'fita bis, pcs 10s', 'Active', 'system', 'system'),
  ('CAN-0395', 'fita bis, pcs', 'Active', 'system', 'system'),
  ('CAN-0396', 'Fudgee Barr 10''s (bag to pcs)1cs-10bg', 'Active', 'system', 'system'),
  ('CAN-0397', 'Fudgee Barr pcs', 'Active', 'system', 'system'),
  ('CAN-0398', 'Hansel 10''s (pck to pcs)', 'Active', 'system', 'system'),
  ('CAN-0399', 'Hello Coated Bis.', 'Active', 'system', 'system'),
  ('CAN-0400', 'Magic Flakes Cheese pck', 'Active', 'system', 'system'),
  ('CAN-0401', 'Magic Flakes Cheese pcs', 'Active', 'system', 'system'),
  ('CAN-0402', 'Nips Tie/pcs', 'Active', 'system', 'system'),
  ('CAN-0403', 'Magic Creams', 'Active', 'system', 'system'),
  ('CAN-0404', 'magic chips pcs', 'Active', 'system', 'system'),
  ('CAN-0405', 'Magic Flakes Chips 100g', 'Active', 'system', 'system'),
  ('CAN-0406', 'Presto Creams 10''s (pck to pcs)', 'Active', 'system', 'system'),
  ('CAN-0407', 'Rebisco Flavor Bunch 20''s', 'Active', 'system', 'system'),
  ('CAN-0408', 'Rebisco Extreme pcs', 'Active', 'system', 'system'),
  ('CAN-0409', 'Rebisco Cracker Bag 20 ''s', 'Active', 'system', 'system'),
  ('CAN-0410', 'Rebisco Cracker Plain 10''s', 'Active', 'system', 'system'),
  ('CAN-0411', 'Butter Coconut pcs', 'Active', 'system', 'system'),
  ('CAN-0412', 'Rebisco Honey Butter pcs', 'Active', 'system', 'system'),
  ('CAN-0413', 'Sweet Jelly Candy', 'Active', 'system', 'system'),
  ('CAN-0414', 'Sweet Jelly pcs', 'Active', 'system', 'system'),
  ('CAN-0415', 'Topps Sarap pcs', 'Active', 'system', 'system'),
  ('CAN-0416', 'Topps Sarap Combo', 'Active', 'system', 'system'),
  ('CAN-0417', 'Wafelo Slug', 'Active', 'system', 'system'),
  ('CAN-0418', 'Whoopie pcs', 'Active', 'system', 'system'),
  ('CAN-0419', 'Valmer Sandwich pck', 'Active', 'system', 'system'),
  ('CAN-0420', 'Valmer Sandwich pcs', 'Active', 'system', 'system'),
  ('CAN-0421', 'Nips Tie/pcs', 'Active', 'system', 'system'),
  ('CAN-0422', 'Palm Oil', 'Active', 'system', 'system'),
  ('CAN-0423', 'Soy Sauce KL', 'Active', 'system', 'system'),
  ('CAN-0424', 'Diswashing Paste smart', 'Active', 'system', 'system'),
  ('CAN-0425', 'Egg', 'Active', 'system', 'system'),
  ('CAN-0426', 'Asin', 'Active', 'system', 'system')
ON CONFLICT (item_code) DO UPDATE SET item_name = EXCLUDED.item_name, status = 'Active', updated_by = 'system', updated_at = CURRENT_TIMESTAMP;

INSERT INTO inventory_item_locations (item_code, location, category_code, display_order, status) VALUES
  ('CAN-0001', 'Canteen A', 'SCHOOL_SUPPLIES', 1, 'Active'),
  ('CAN-0001', 'Canteen B', 'SCHOOL_SUPPLIES', 1, 'Active'),
  ('CAN-0002', 'Canteen A', 'SCHOOL_SUPPLIES', 2, 'Active'),
  ('CAN-0002', 'Canteen B', 'SCHOOL_SUPPLIES', 2, 'Active'),
  ('CAN-0003', 'Canteen A', 'SCHOOL_SUPPLIES', 3, 'Active'),
  ('CAN-0003', 'Canteen B', 'SCHOOL_SUPPLIES', 3, 'Active'),
  ('CAN-0004', 'Canteen A', 'SCHOOL_SUPPLIES', 4, 'Active'),
  ('CAN-0004', 'Canteen B', 'SCHOOL_SUPPLIES', 4, 'Active'),
  ('CAN-0005', 'Canteen A', 'SCHOOL_SUPPLIES', 5, 'Active'),
  ('CAN-0005', 'Canteen B', 'SCHOOL_SUPPLIES', 5, 'Active'),
  ('CAN-0006', 'Canteen A', 'SCHOOL_SUPPLIES', 6, 'Active'),
  ('CAN-0006', 'Canteen B', 'SCHOOL_SUPPLIES', 6, 'Active'),
  ('CAN-0007', 'Canteen A', 'SCHOOL_SUPPLIES', 7, 'Active'),
  ('CAN-0007', 'Canteen B', 'SCHOOL_SUPPLIES', 7, 'Active'),
  ('CAN-0008', 'Canteen A', 'SCHOOL_SUPPLIES', 8, 'Active'),
  ('CAN-0008', 'Canteen B', 'SCHOOL_SUPPLIES', 8, 'Active'),
  ('CAN-0009', 'Canteen A', 'SCHOOL_SUPPLIES', 9, 'Active'),
  ('CAN-0009', 'Canteen B', 'SCHOOL_SUPPLIES', 9, 'Active'),
  ('CAN-0010', 'Canteen A', 'SCHOOL_SUPPLIES', 10, 'Active'),
  ('CAN-0010', 'Canteen B', 'SCHOOL_SUPPLIES', 10, 'Active'),
  ('CAN-0011', 'Canteen A', 'SCHOOL_SUPPLIES', 11, 'Active'),
  ('CAN-0011', 'Canteen B', 'SCHOOL_SUPPLIES', 11, 'Active'),
  ('CAN-0012', 'Canteen A', 'SCHOOL_SUPPLIES', 12, 'Active'),
  ('CAN-0012', 'Canteen B', 'SCHOOL_SUPPLIES', 12, 'Active'),
  ('CAN-0013', 'Canteen A', 'SCHOOL_SUPPLIES', 13, 'Active'),
  ('CAN-0013', 'Canteen B', 'SCHOOL_SUPPLIES', 13, 'Active'),
  ('CAN-0014', 'Canteen A', 'SCHOOL_SUPPLIES', 14, 'Active'),
  ('CAN-0014', 'Canteen B', 'SCHOOL_SUPPLIES', 14, 'Active'),
  ('CAN-0015', 'Canteen A', 'SCHOOL_SUPPLIES', 15, 'Active'),
  ('CAN-0015', 'Canteen B', 'SCHOOL_SUPPLIES', 15, 'Active'),
  ('CAN-0016', 'Canteen A', 'SCHOOL_SUPPLIES', 16, 'Active'),
  ('CAN-0016', 'Canteen B', 'SCHOOL_SUPPLIES', 16, 'Active'),
  ('CAN-0017', 'Canteen A', 'SCHOOL_SUPPLIES', 17, 'Active'),
  ('CAN-0017', 'Canteen B', 'SCHOOL_SUPPLIES', 17, 'Active'),
  ('CAN-0018', 'Canteen A', 'SCHOOL_SUPPLIES', 18, 'Active'),
  ('CAN-0018', 'Canteen B', 'SCHOOL_SUPPLIES', 18, 'Active'),
  ('CAN-0019', 'Canteen A', 'SCHOOL_SUPPLIES', 19, 'Active'),
  ('CAN-0019', 'Canteen B', 'SCHOOL_SUPPLIES', 19, 'Active'),
  ('CAN-0020', 'Canteen A', 'SCHOOL_SUPPLIES', 20, 'Active'),
  ('CAN-0020', 'Canteen B', 'SCHOOL_SUPPLIES', 20, 'Active'),
  ('CAN-0021', 'Canteen A', 'SCHOOL_SUPPLIES', 21, 'Active'),
  ('CAN-0021', 'Canteen B', 'SCHOOL_SUPPLIES', 21, 'Active'),
  ('CAN-0022', 'Canteen A', 'SCHOOL_SUPPLIES', 22, 'Active'),
  ('CAN-0022', 'Canteen B', 'SCHOOL_SUPPLIES', 22, 'Active'),
  ('CAN-0023', 'Canteen A', 'SCHOOL_SUPPLIES', 23, 'Active'),
  ('CAN-0023', 'Canteen B', 'SCHOOL_SUPPLIES', 23, 'Active'),
  ('CAN-0024', 'Canteen A', 'SCHOOL_SUPPLIES', 24, 'Active'),
  ('CAN-0024', 'Canteen B', 'SCHOOL_SUPPLIES', 24, 'Active'),
  ('CAN-0025', 'Canteen A', 'SCHOOL_SUPPLIES', 25, 'Active'),
  ('CAN-0025', 'Canteen B', 'SCHOOL_SUPPLIES', 25, 'Active'),
  ('CAN-0026', 'Canteen A', 'SCHOOL_SUPPLIES', 26, 'Active'),
  ('CAN-0026', 'Canteen B', 'SCHOOL_SUPPLIES', 26, 'Active'),
  ('CAN-0027', 'Canteen A', 'SCHOOL_SUPPLIES', 27, 'Active'),
  ('CAN-0027', 'Canteen B', 'SCHOOL_SUPPLIES', 27, 'Active'),
  ('CAN-0028', 'Canteen A', 'SCHOOL_SUPPLIES', 28, 'Active'),
  ('CAN-0028', 'Canteen B', 'SCHOOL_SUPPLIES', 28, 'Active'),
  ('CAN-0029', 'Canteen A', 'SCHOOL_SUPPLIES', 29, 'Active'),
  ('CAN-0029', 'Canteen B', 'SCHOOL_SUPPLIES', 29, 'Active'),
  ('CAN-0030', 'Canteen A', 'SCHOOL_SUPPLIES', 30, 'Active'),
  ('CAN-0030', 'Canteen B', 'SCHOOL_SUPPLIES', 30, 'Active'),
  ('CAN-0031', 'Canteen A', 'SCHOOL_SUPPLIES', 31, 'Active'),
  ('CAN-0031', 'Canteen B', 'SCHOOL_SUPPLIES', 31, 'Active'),
  ('CAN-0032', 'Canteen A', 'SCHOOL_SUPPLIES', 32, 'Active'),
  ('CAN-0032', 'Canteen B', 'SCHOOL_SUPPLIES', 32, 'Active'),
  ('CAN-0033', 'Canteen A', 'SCHOOL_SUPPLIES', 33, 'Active'),
  ('CAN-0033', 'Canteen B', 'SCHOOL_SUPPLIES', 33, 'Active'),
  ('CAN-0034', 'Canteen A', 'SCHOOL_SUPPLIES', 34, 'Active'),
  ('CAN-0034', 'Canteen B', 'SCHOOL_SUPPLIES', 34, 'Active'),
  ('CAN-0035', 'Canteen A', 'SCHOOL_SUPPLIES', 35, 'Active'),
  ('CAN-0035', 'Canteen B', 'SCHOOL_SUPPLIES', 35, 'Active'),
  ('CAN-0036', 'Canteen A', 'SCHOOL_SUPPLIES', 36, 'Active'),
  ('CAN-0036', 'Canteen B', 'SCHOOL_SUPPLIES', 36, 'Active'),
  ('CAN-0037', 'Canteen A', 'SCHOOL_SUPPLIES', 37, 'Active'),
  ('CAN-0037', 'Canteen B', 'SCHOOL_SUPPLIES', 37, 'Active'),
  ('CAN-0038', 'Canteen A', 'SCHOOL_SUPPLIES', 38, 'Active'),
  ('CAN-0038', 'Canteen B', 'SCHOOL_SUPPLIES', 38, 'Active'),
  ('CAN-0039', 'Canteen A', 'SCHOOL_SUPPLIES', 39, 'Active'),
  ('CAN-0039', 'Canteen B', 'SCHOOL_SUPPLIES', 39, 'Active'),
  ('CAN-0040', 'Canteen A', 'SCHOOL_SUPPLIES', 40, 'Active'),
  ('CAN-0040', 'Canteen B', 'SCHOOL_SUPPLIES', 40, 'Active'),
  ('CAN-0041', 'Canteen A', 'SCHOOL_SUPPLIES', 41, 'Active'),
  ('CAN-0041', 'Canteen B', 'SCHOOL_SUPPLIES', 41, 'Active'),
  ('CAN-0042', 'Canteen A', 'SCHOOL_SUPPLIES', 42, 'Active'),
  ('CAN-0042', 'Canteen B', 'SCHOOL_SUPPLIES', 42, 'Active'),
  ('CAN-0043', 'Canteen A', 'SCHOOL_SUPPLIES', 43, 'Active'),
  ('CAN-0043', 'Canteen B', 'SCHOOL_SUPPLIES', 43, 'Active'),
  ('CAN-0044', 'Canteen A', 'SCHOOL_SUPPLIES', 44, 'Active'),
  ('CAN-0044', 'Canteen B', 'SCHOOL_SUPPLIES', 44, 'Active'),
  ('CAN-0045', 'Canteen A', 'SCHOOL_SUPPLIES', 45, 'Active'),
  ('CAN-0045', 'Canteen B', 'SCHOOL_SUPPLIES', 45, 'Active'),
  ('CAN-0046', 'Canteen A', 'SCHOOL_SUPPLIES', 46, 'Active'),
  ('CAN-0046', 'Canteen B', 'SCHOOL_SUPPLIES', 46, 'Active'),
  ('CAN-0047', 'Canteen A', 'SCHOOL_SUPPLIES', 47, 'Active'),
  ('CAN-0047', 'Canteen B', 'SCHOOL_SUPPLIES', 47, 'Active'),
  ('CAN-0048', 'Canteen A', 'SCHOOL_SUPPLIES', 48, 'Active'),
  ('CAN-0048', 'Canteen B', 'SCHOOL_SUPPLIES', 48, 'Active'),
  ('CAN-0049', 'Canteen A', 'SCHOOL_SUPPLIES', 49, 'Active'),
  ('CAN-0049', 'Canteen B', 'SCHOOL_SUPPLIES', 49, 'Active'),
  ('CAN-0050', 'Canteen A', 'SCHOOL_SUPPLIES', 50, 'Active'),
  ('CAN-0050', 'Canteen B', 'SCHOOL_SUPPLIES', 50, 'Active'),
  ('CAN-0051', 'Canteen A', 'SCHOOL_SUPPLIES', 51, 'Active'),
  ('CAN-0051', 'Canteen B', 'SCHOOL_SUPPLIES', 51, 'Active'),
  ('CAN-0052', 'Canteen A', 'SCHOOL_SUPPLIES', 52, 'Active'),
  ('CAN-0052', 'Canteen B', 'SCHOOL_SUPPLIES', 52, 'Active'),
  ('CAN-0053', 'Canteen A', 'SCHOOL_SUPPLIES', 53, 'Active'),
  ('CAN-0053', 'Canteen B', 'SCHOOL_SUPPLIES', 53, 'Active'),
  ('CAN-0054', 'Canteen A', 'SCHOOL_SUPPLIES', 54, 'Active'),
  ('CAN-0054', 'Canteen B', 'SCHOOL_SUPPLIES', 54, 'Active'),
  ('CAN-0055', 'Canteen A', 'SCHOOL_SUPPLIES', 55, 'Active'),
  ('CAN-0055', 'Canteen B', 'SCHOOL_SUPPLIES', 55, 'Active'),
  ('CAN-0056', 'Canteen A', 'SCHOOL_SUPPLIES', 56, 'Active'),
  ('CAN-0056', 'Canteen B', 'SCHOOL_SUPPLIES', 56, 'Active'),
  ('CAN-0057', 'Canteen A', 'SCHOOL_SUPPLIES', 57, 'Active'),
  ('CAN-0057', 'Canteen B', 'SCHOOL_SUPPLIES', 57, 'Active'),
  ('CAN-0058', 'Canteen A', 'SCHOOL_SUPPLIES', 58, 'Active'),
  ('CAN-0058', 'Canteen B', 'SCHOOL_SUPPLIES', 58, 'Active'),
  ('CAN-0059', 'Canteen A', 'SCHOOL_SUPPLIES', 59, 'Active'),
  ('CAN-0059', 'Canteen B', 'SCHOOL_SUPPLIES', 59, 'Active'),
  ('CAN-0060', 'Canteen A', 'SCHOOL_SUPPLIES', 60, 'Active'),
  ('CAN-0060', 'Canteen B', 'SCHOOL_SUPPLIES', 60, 'Active'),
  ('CAN-0061', 'Canteen A', 'SCHOOL_SUPPLIES', 61, 'Active'),
  ('CAN-0061', 'Canteen B', 'SCHOOL_SUPPLIES', 61, 'Active'),
  ('CAN-0062', 'Canteen A', 'SCHOOL_SUPPLIES', 62, 'Active'),
  ('CAN-0062', 'Canteen B', 'SCHOOL_SUPPLIES', 62, 'Active'),
  ('CAN-0063', 'Canteen A', 'SCHOOL_SUPPLIES', 63, 'Active'),
  ('CAN-0063', 'Canteen B', 'SCHOOL_SUPPLIES', 63, 'Active'),
  ('CAN-0064', 'Canteen A', 'SCHOOL_SUPPLIES', 64, 'Active'),
  ('CAN-0064', 'Canteen B', 'SCHOOL_SUPPLIES', 64, 'Active'),
  ('CAN-0065', 'Canteen A', 'SCHOOL_SUPPLIES', 65, 'Active'),
  ('CAN-0065', 'Canteen B', 'SCHOOL_SUPPLIES', 65, 'Active'),
  ('CAN-0066', 'Canteen A', 'SCHOOL_SUPPLIES', 66, 'Active'),
  ('CAN-0066', 'Canteen B', 'SCHOOL_SUPPLIES', 66, 'Active'),
  ('CAN-0067', 'Canteen A', 'SCHOOL_SUPPLIES', 67, 'Active'),
  ('CAN-0067', 'Canteen B', 'SCHOOL_SUPPLIES', 67, 'Active'),
  ('CAN-0068', 'Canteen A', 'SCHOOL_SUPPLIES', 68, 'Active'),
  ('CAN-0068', 'Canteen B', 'SCHOOL_SUPPLIES', 68, 'Active'),
  ('CAN-0069', 'Canteen A', 'SCHOOL_SUPPLIES', 69, 'Active'),
  ('CAN-0069', 'Canteen B', 'SCHOOL_SUPPLIES', 69, 'Active'),
  ('CAN-0070', 'Canteen A', 'SCHOOL_SUPPLIES', 70, 'Active'),
  ('CAN-0070', 'Canteen B', 'SCHOOL_SUPPLIES', 70, 'Active'),
  ('CAN-0071', 'Canteen A', 'SCHOOL_SUPPLIES', 71, 'Active'),
  ('CAN-0071', 'Canteen B', 'SCHOOL_SUPPLIES', 71, 'Active'),
  ('CAN-0072', 'Canteen A', 'SCHOOL_SUPPLIES', 72, 'Active'),
  ('CAN-0072', 'Canteen B', 'SCHOOL_SUPPLIES', 72, 'Active'),
  ('CAN-0073', 'Canteen A', 'SCHOOL_SUPPLIES', 73, 'Active'),
  ('CAN-0073', 'Canteen B', 'SCHOOL_SUPPLIES', 73, 'Active'),
  ('CAN-0074', 'Canteen A', 'SCHOOL_SUPPLIES', 74, 'Active'),
  ('CAN-0074', 'Canteen B', 'SCHOOL_SUPPLIES', 74, 'Active'),
  ('CAN-0075', 'Canteen A', 'SCHOOL_SUPPLIES', 75, 'Active'),
  ('CAN-0075', 'Canteen B', 'SCHOOL_SUPPLIES', 75, 'Active'),
  ('CAN-0076', 'Canteen A', 'SCHOOL_SUPPLIES', 76, 'Active'),
  ('CAN-0076', 'Canteen B', 'SCHOOL_SUPPLIES', 76, 'Active'),
  ('CAN-0077', 'Canteen A', 'SCHOOL_SUPPLIES', 77, 'Active'),
  ('CAN-0077', 'Canteen B', 'SCHOOL_SUPPLIES', 77, 'Active'),
  ('CAN-0078', 'Canteen A', 'SCHOOL_SUPPLIES', 78, 'Active'),
  ('CAN-0078', 'Canteen B', 'SCHOOL_SUPPLIES', 78, 'Active'),
  ('CAN-0079', 'Canteen A', 'SCHOOL_SUPPLIES', 79, 'Active'),
  ('CAN-0079', 'Canteen B', 'SCHOOL_SUPPLIES', 79, 'Active'),
  ('CAN-0080', 'Canteen A', 'SCHOOL_SUPPLIES', 80, 'Active'),
  ('CAN-0080', 'Canteen B', 'SCHOOL_SUPPLIES', 80, 'Active'),
  ('CAN-0081', 'Canteen A', 'SCHOOL_SUPPLIES', 81, 'Active'),
  ('CAN-0081', 'Canteen B', 'SCHOOL_SUPPLIES', 81, 'Active'),
  ('CAN-0082', 'Canteen A', 'SCHOOL_SUPPLIES', 82, 'Active'),
  ('CAN-0082', 'Canteen B', 'SCHOOL_SUPPLIES', 82, 'Active'),
  ('CAN-0083', 'Canteen A', 'SCHOOL_SUPPLIES', 83, 'Active'),
  ('CAN-0083', 'Canteen B', 'SCHOOL_SUPPLIES', 83, 'Active'),
  ('CAN-0084', 'Canteen A', 'SCHOOL_SUPPLIES', 84, 'Active'),
  ('CAN-0084', 'Canteen B', 'SCHOOL_SUPPLIES', 84, 'Active'),
  ('CAN-0085', 'Canteen A', 'SCHOOL_SUPPLIES', 85, 'Active'),
  ('CAN-0085', 'Canteen B', 'SCHOOL_SUPPLIES', 85, 'Active'),
  ('CAN-0086', 'Canteen A', 'SCHOOL_SUPPLIES', 86, 'Active'),
  ('CAN-0086', 'Canteen B', 'SCHOOL_SUPPLIES', 86, 'Active'),
  ('CAN-0087', 'Canteen A', 'SCHOOL_SUPPLIES', 87, 'Active'),
  ('CAN-0087', 'Canteen B', 'SCHOOL_SUPPLIES', 87, 'Active'),
  ('CAN-0088', 'Canteen A', 'SCHOOL_SUPPLIES', 88, 'Active'),
  ('CAN-0088', 'Canteen B', 'SCHOOL_SUPPLIES', 88, 'Active'),
  ('CAN-0089', 'Canteen A', 'SCHOOL_SUPPLIES', 89, 'Active'),
  ('CAN-0089', 'Canteen B', 'SCHOOL_SUPPLIES', 89, 'Active'),
  ('CAN-0090', 'Canteen A', 'SCHOOL_SUPPLIES', 90, 'Active'),
  ('CAN-0090', 'Canteen B', 'SCHOOL_SUPPLIES', 90, 'Active'),
  ('CAN-0091', 'Canteen A', 'SCHOOL_SUPPLIES', 91, 'Active'),
  ('CAN-0091', 'Canteen B', 'SCHOOL_SUPPLIES', 91, 'Active'),
  ('CAN-0092', 'Canteen A', 'SCHOOL_SUPPLIES', 92, 'Active'),
  ('CAN-0092', 'Canteen B', 'SCHOOL_SUPPLIES', 92, 'Active'),
  ('CAN-0093', 'Canteen A', 'SCHOOL_SUPPLIES', 93, 'Active'),
  ('CAN-0093', 'Canteen B', 'SCHOOL_SUPPLIES', 93, 'Active'),
  ('CAN-0094', 'Canteen A', 'SCHOOL_SUPPLIES', 94, 'Active'),
  ('CAN-0094', 'Canteen B', 'SCHOOL_SUPPLIES', 94, 'Active'),
  ('CAN-0095', 'Canteen A', 'SCHOOL_SUPPLIES', 95, 'Active'),
  ('CAN-0095', 'Canteen B', 'SCHOOL_SUPPLIES', 95, 'Active'),
  ('CAN-0096', 'Canteen A', 'SCHOOL_SUPPLIES', 96, 'Active'),
  ('CAN-0096', 'Canteen B', 'SCHOOL_SUPPLIES', 96, 'Active'),
  ('CAN-0097', 'Canteen A', 'SCHOOL_SUPPLIES', 97, 'Active'),
  ('CAN-0097', 'Canteen B', 'SCHOOL_SUPPLIES', 97, 'Active'),
  ('CAN-0098', 'Canteen A', 'SCHOOL_SUPPLIES', 98, 'Active'),
  ('CAN-0098', 'Canteen B', 'SCHOOL_SUPPLIES', 98, 'Active'),
  ('CAN-0099', 'Canteen A', 'SCHOOL_SUPPLIES', 99, 'Active'),
  ('CAN-0099', 'Canteen B', 'SCHOOL_SUPPLIES', 99, 'Active'),
  ('CAN-0100', 'Canteen A', 'TOILETRIES_MEDICINE', 1, 'Active'),
  ('CAN-0100', 'Canteen B', 'TOILETRIES_MEDICINE', 1, 'Active'),
  ('CAN-0101', 'Canteen A', 'TOILETRIES_MEDICINE', 2, 'Active'),
  ('CAN-0101', 'Canteen B', 'TOILETRIES_MEDICINE', 2, 'Active'),
  ('CAN-0102', 'Canteen A', 'TOILETRIES_MEDICINE', 3, 'Active'),
  ('CAN-0102', 'Canteen B', 'TOILETRIES_MEDICINE', 3, 'Active'),
  ('CAN-0103', 'Canteen A', 'TOILETRIES_MEDICINE', 4, 'Active'),
  ('CAN-0103', 'Canteen B', 'TOILETRIES_MEDICINE', 4, 'Active'),
  ('CAN-0104', 'Canteen A', 'TOILETRIES_MEDICINE', 5, 'Active'),
  ('CAN-0104', 'Canteen B', 'TOILETRIES_MEDICINE', 5, 'Active'),
  ('CAN-0105', 'Canteen A', 'TOILETRIES_MEDICINE', 6, 'Active'),
  ('CAN-0105', 'Canteen B', 'TOILETRIES_MEDICINE', 6, 'Active'),
  ('CAN-0106', 'Canteen A', 'TOILETRIES_MEDICINE', 7, 'Active'),
  ('CAN-0106', 'Canteen B', 'TOILETRIES_MEDICINE', 7, 'Active'),
  ('CAN-0107', 'Canteen A', 'TOILETRIES_MEDICINE', 8, 'Active'),
  ('CAN-0107', 'Canteen B', 'TOILETRIES_MEDICINE', 8, 'Active'),
  ('CAN-0108', 'Canteen A', 'TOILETRIES_MEDICINE', 9, 'Active'),
  ('CAN-0108', 'Canteen B', 'TOILETRIES_MEDICINE', 9, 'Active'),
  ('CAN-0109', 'Canteen A', 'TOILETRIES_MEDICINE', 10, 'Active'),
  ('CAN-0109', 'Canteen B', 'TOILETRIES_MEDICINE', 10, 'Active'),
  ('CAN-0110', 'Canteen A', 'TOILETRIES_MEDICINE', 11, 'Active'),
  ('CAN-0110', 'Canteen B', 'TOILETRIES_MEDICINE', 11, 'Active'),
  ('CAN-0111', 'Canteen A', 'TOILETRIES_MEDICINE', 12, 'Active'),
  ('CAN-0111', 'Canteen B', 'TOILETRIES_MEDICINE', 12, 'Active'),
  ('CAN-0112', 'Canteen A', 'TOILETRIES_MEDICINE', 13, 'Active'),
  ('CAN-0112', 'Canteen B', 'TOILETRIES_MEDICINE', 13, 'Active'),
  ('CAN-0113', 'Canteen A', 'TOILETRIES_MEDICINE', 14, 'Active'),
  ('CAN-0113', 'Canteen B', 'TOILETRIES_MEDICINE', 14, 'Active'),
  ('CAN-0114', 'Canteen A', 'TOILETRIES_MEDICINE', 15, 'Active'),
  ('CAN-0114', 'Canteen B', 'TOILETRIES_MEDICINE', 15, 'Active'),
  ('CAN-0115', 'Canteen A', 'TOILETRIES_MEDICINE', 16, 'Active'),
  ('CAN-0115', 'Canteen B', 'TOILETRIES_MEDICINE', 16, 'Active'),
  ('CAN-0116', 'Canteen A', 'TOILETRIES_MEDICINE', 17, 'Active'),
  ('CAN-0116', 'Canteen B', 'TOILETRIES_MEDICINE', 17, 'Active'),
  ('CAN-0117', 'Canteen A', 'TOILETRIES_MEDICINE', 18, 'Active'),
  ('CAN-0117', 'Canteen B', 'TOILETRIES_MEDICINE', 18, 'Active'),
  ('CAN-0118', 'Canteen A', 'TOILETRIES_MEDICINE', 19, 'Active'),
  ('CAN-0118', 'Canteen B', 'TOILETRIES_MEDICINE', 19, 'Active'),
  ('CAN-0119', 'Canteen A', 'TOILETRIES_MEDICINE', 20, 'Active'),
  ('CAN-0119', 'Canteen B', 'TOILETRIES_MEDICINE', 20, 'Active'),
  ('CAN-0120', 'Canteen A', 'TOILETRIES_MEDICINE', 21, 'Active'),
  ('CAN-0120', 'Canteen B', 'TOILETRIES_MEDICINE', 21, 'Active'),
  ('CAN-0121', 'Canteen A', 'TOILETRIES_MEDICINE', 22, 'Active'),
  ('CAN-0121', 'Canteen B', 'TOILETRIES_MEDICINE', 22, 'Active'),
  ('CAN-0122', 'Canteen A', 'TOILETRIES_MEDICINE', 23, 'Active'),
  ('CAN-0122', 'Canteen B', 'TOILETRIES_MEDICINE', 23, 'Active'),
  ('CAN-0123', 'Canteen A', 'TOILETRIES_MEDICINE', 24, 'Active'),
  ('CAN-0123', 'Canteen B', 'TOILETRIES_MEDICINE', 24, 'Active'),
  ('CAN-0124', 'Canteen A', 'TOILETRIES_MEDICINE', 25, 'Active'),
  ('CAN-0124', 'Canteen B', 'TOILETRIES_MEDICINE', 25, 'Active'),
  ('CAN-0125', 'Canteen A', 'TOILETRIES_MEDICINE', 26, 'Active'),
  ('CAN-0125', 'Canteen B', 'TOILETRIES_MEDICINE', 26, 'Active'),
  ('CAN-0126', 'Canteen A', 'TOILETRIES_MEDICINE', 27, 'Active'),
  ('CAN-0126', 'Canteen B', 'TOILETRIES_MEDICINE', 27, 'Active'),
  ('CAN-0127', 'Canteen A', 'TOILETRIES_MEDICINE', 28, 'Active'),
  ('CAN-0127', 'Canteen B', 'TOILETRIES_MEDICINE', 28, 'Active'),
  ('CAN-0128', 'Canteen A', 'TOILETRIES_MEDICINE', 29, 'Active'),
  ('CAN-0128', 'Canteen B', 'TOILETRIES_MEDICINE', 29, 'Active'),
  ('CAN-0129', 'Canteen A', 'TOILETRIES_MEDICINE', 30, 'Active'),
  ('CAN-0129', 'Canteen B', 'TOILETRIES_MEDICINE', 30, 'Active'),
  ('CAN-0130', 'Canteen A', 'TOILETRIES_MEDICINE', 31, 'Active'),
  ('CAN-0130', 'Canteen B', 'TOILETRIES_MEDICINE', 31, 'Active'),
  ('CAN-0131', 'Canteen A', 'TOILETRIES_MEDICINE', 32, 'Active'),
  ('CAN-0131', 'Canteen B', 'TOILETRIES_MEDICINE', 32, 'Active'),
  ('CAN-0132', 'Canteen A', 'TOILETRIES_MEDICINE', 33, 'Active'),
  ('CAN-0132', 'Canteen B', 'TOILETRIES_MEDICINE', 33, 'Active'),
  ('CAN-0133', 'Canteen A', 'TOILETRIES_MEDICINE', 34, 'Active'),
  ('CAN-0133', 'Canteen B', 'TOILETRIES_MEDICINE', 34, 'Active'),
  ('CAN-0134', 'Canteen A', 'TOILETRIES_MEDICINE', 35, 'Active'),
  ('CAN-0134', 'Canteen B', 'TOILETRIES_MEDICINE', 35, 'Active'),
  ('CAN-0135', 'Canteen A', 'TOILETRIES_MEDICINE', 36, 'Active'),
  ('CAN-0135', 'Canteen B', 'TOILETRIES_MEDICINE', 36, 'Active'),
  ('CAN-0136', 'Canteen A', 'TOILETRIES_MEDICINE', 37, 'Active'),
  ('CAN-0136', 'Canteen B', 'TOILETRIES_MEDICINE', 37, 'Active'),
  ('CAN-0137', 'Canteen A', 'TOILETRIES_MEDICINE', 38, 'Active'),
  ('CAN-0137', 'Canteen B', 'TOILETRIES_MEDICINE', 38, 'Active'),
  ('CAN-0138', 'Canteen A', 'TOILETRIES_MEDICINE', 39, 'Active'),
  ('CAN-0138', 'Canteen B', 'TOILETRIES_MEDICINE', 39, 'Active'),
  ('CAN-0139', 'Canteen A', 'CANNED_DRINKS', 1, 'Active'),
  ('CAN-0139', 'Canteen B', 'CANNED_DRINKS', 1, 'Active'),
  ('CAN-0140', 'Canteen A', 'CANNED_DRINKS', 2, 'Active'),
  ('CAN-0140', 'Canteen B', 'CANNED_DRINKS', 2, 'Active'),
  ('CAN-0141', 'Canteen A', 'CANNED_DRINKS', 3, 'Active'),
  ('CAN-0141', 'Canteen B', 'CANNED_DRINKS', 3, 'Active'),
  ('CAN-0142', 'Canteen A', 'CANNED_DRINKS', 4, 'Active'),
  ('CAN-0142', 'Canteen B', 'CANNED_DRINKS', 4, 'Active'),
  ('CAN-0143', 'Canteen A', 'CANNED_DRINKS', 5, 'Active'),
  ('CAN-0143', 'Canteen B', 'CANNED_DRINKS', 5, 'Active'),
  ('CAN-0144', 'Canteen A', 'CANNED_DRINKS', 6, 'Active'),
  ('CAN-0144', 'Canteen B', 'CANNED_DRINKS', 6, 'Active'),
  ('CAN-0145', 'Canteen A', 'CANNED_DRINKS', 7, 'Active'),
  ('CAN-0145', 'Canteen B', 'CANNED_DRINKS', 7, 'Active'),
  ('CAN-0146', 'Canteen A', 'CANNED_DRINKS', 8, 'Active'),
  ('CAN-0146', 'Canteen B', 'CANNED_DRINKS', 8, 'Active'),
  ('CAN-0147', 'Canteen A', 'CANNED_DRINKS', 9, 'Active'),
  ('CAN-0147', 'Canteen B', 'CANNED_DRINKS', 9, 'Active'),
  ('CAN-0148', 'Canteen A', 'CANNED_DRINKS', 10, 'Active'),
  ('CAN-0148', 'Canteen B', 'CANNED_DRINKS', 10, 'Active'),
  ('CAN-0149', 'Canteen A', 'CANNED_DRINKS', 11, 'Active'),
  ('CAN-0149', 'Canteen B', 'CANNED_DRINKS', 11, 'Active'),
  ('CAN-0150', 'Canteen A', 'CANNED_DRINKS', 12, 'Active'),
  ('CAN-0150', 'Canteen B', 'CANNED_DRINKS', 12, 'Active'),
  ('CAN-0151', 'Canteen A', 'CANNED_DRINKS', 13, 'Active'),
  ('CAN-0151', 'Canteen B', 'CANNED_DRINKS', 13, 'Active'),
  ('CAN-0152', 'Canteen A', 'CANNED_DRINKS', 14, 'Active'),
  ('CAN-0152', 'Canteen B', 'CANNED_DRINKS', 14, 'Active'),
  ('CAN-0153', 'Canteen A', 'CANNED_DRINKS', 15, 'Active'),
  ('CAN-0153', 'Canteen B', 'CANNED_DRINKS', 15, 'Active'),
  ('CAN-0154', 'Canteen A', 'CANNED_DRINKS', 16, 'Active'),
  ('CAN-0154', 'Canteen B', 'CANNED_DRINKS', 16, 'Active'),
  ('CAN-0155', 'Canteen A', 'CANNED_DRINKS', 17, 'Active'),
  ('CAN-0155', 'Canteen B', 'CANNED_DRINKS', 17, 'Active'),
  ('CAN-0156', 'Canteen A', 'CANNED_DRINKS', 18, 'Active'),
  ('CAN-0156', 'Canteen B', 'CANNED_DRINKS', 18, 'Active'),
  ('CAN-0157', 'Canteen A', 'CANNED_DRINKS', 19, 'Active'),
  ('CAN-0157', 'Canteen B', 'CANNED_DRINKS', 19, 'Active'),
  ('CAN-0158', 'Canteen A', 'CANNED_DRINKS', 20, 'Active'),
  ('CAN-0158', 'Canteen B', 'CANNED_DRINKS', 20, 'Active'),
  ('CAN-0159', 'Canteen A', 'CANNED_DRINKS', 21, 'Active'),
  ('CAN-0159', 'Canteen B', 'CANNED_DRINKS', 21, 'Active'),
  ('CAN-0160', 'Canteen A', 'CANNED_DRINKS', 22, 'Active'),
  ('CAN-0160', 'Canteen B', 'CANNED_DRINKS', 22, 'Active'),
  ('CAN-0161', 'Canteen A', 'CANNED_DRINKS', 23, 'Active'),
  ('CAN-0161', 'Canteen B', 'CANNED_DRINKS', 23, 'Active'),
  ('CAN-0162', 'Canteen A', 'CANNED_DRINKS', 24, 'Active'),
  ('CAN-0162', 'Canteen B', 'CANNED_DRINKS', 24, 'Active'),
  ('CAN-0163', 'Canteen A', 'CANNED_DRINKS', 25, 'Active'),
  ('CAN-0163', 'Canteen B', 'CANNED_DRINKS', 25, 'Active'),
  ('CAN-0164', 'Canteen A', 'CANNED_DRINKS', 26, 'Active'),
  ('CAN-0164', 'Canteen B', 'CANNED_DRINKS', 26, 'Active'),
  ('CAN-0165', 'Canteen A', 'CANNED_DRINKS', 27, 'Active'),
  ('CAN-0165', 'Canteen B', 'CANNED_DRINKS', 27, 'Active'),
  ('CAN-0166', 'Canteen A', 'CANNED_DRINKS', 28, 'Active'),
  ('CAN-0166', 'Canteen B', 'CANNED_DRINKS', 28, 'Active'),
  ('CAN-0167', 'Canteen A', 'CANNED_DRINKS', 29, 'Active'),
  ('CAN-0167', 'Canteen B', 'CANNED_DRINKS', 29, 'Active'),
  ('CAN-0168', 'Canteen A', 'CANNED_DRINKS', 30, 'Active'),
  ('CAN-0168', 'Canteen B', 'CANNED_DRINKS', 30, 'Active'),
  ('CAN-0169', 'Canteen A', 'CANNED_DRINKS', 31, 'Active'),
  ('CAN-0169', 'Canteen B', 'CANNED_DRINKS', 31, 'Active'),
  ('CAN-0170', 'Canteen A', 'CANNED_DRINKS', 32, 'Active'),
  ('CAN-0170', 'Canteen B', 'CANNED_DRINKS', 32, 'Active'),
  ('CAN-0171', 'Canteen A', 'CANNED_DRINKS', 33, 'Active'),
  ('CAN-0171', 'Canteen B', 'CANNED_DRINKS', 33, 'Active'),
  ('CAN-0172', 'Canteen A', 'CANNED_DRINKS', 34, 'Active'),
  ('CAN-0172', 'Canteen B', 'CANNED_DRINKS', 34, 'Active'),
  ('CAN-0173', 'Canteen A', 'CANNED_DRINKS', 35, 'Active'),
  ('CAN-0173', 'Canteen B', 'CANNED_DRINKS', 35, 'Active'),
  ('CAN-0174', 'Canteen A', 'CANNED_DRINKS', 36, 'Active'),
  ('CAN-0174', 'Canteen B', 'CANNED_DRINKS', 36, 'Active'),
  ('CAN-0175', 'Canteen A', 'CANNED_DRINKS', 37, 'Active'),
  ('CAN-0175', 'Canteen B', 'CANNED_DRINKS', 37, 'Active'),
  ('CAN-0176', 'Canteen A', 'CANNED_DRINKS', 38, 'Active'),
  ('CAN-0176', 'Canteen B', 'CANNED_DRINKS', 38, 'Active'),
  ('CAN-0177', 'Canteen A', 'CANNED_DRINKS', 39, 'Active'),
  ('CAN-0177', 'Canteen B', 'CANNED_DRINKS', 39, 'Active'),
  ('CAN-0178', 'Canteen A', 'CANNED_DRINKS', 40, 'Active'),
  ('CAN-0178', 'Canteen B', 'CANNED_DRINKS', 40, 'Active'),
  ('CAN-0179', 'Canteen A', 'CANNED_DRINKS', 41, 'Active'),
  ('CAN-0179', 'Canteen B', 'CANNED_DRINKS', 41, 'Active'),
  ('CAN-0180', 'Canteen A', 'CANNED_DRINKS', 42, 'Active'),
  ('CAN-0180', 'Canteen B', 'CANNED_DRINKS', 42, 'Active'),
  ('CAN-0181', 'Canteen A', 'CANNED_DRINKS', 43, 'Active'),
  ('CAN-0181', 'Canteen B', 'CANNED_DRINKS', 43, 'Active'),
  ('CAN-0182', 'Canteen A', 'CANNED_DRINKS', 44, 'Active'),
  ('CAN-0182', 'Canteen B', 'CANNED_DRINKS', 44, 'Active'),
  ('CAN-0183', 'Canteen A', 'CANNED_DRINKS', 45, 'Active'),
  ('CAN-0183', 'Canteen B', 'CANNED_DRINKS', 45, 'Active'),
  ('CAN-0184', 'Canteen A', 'CANNED_DRINKS', 46, 'Active'),
  ('CAN-0184', 'Canteen B', 'CANNED_DRINKS', 46, 'Active'),
  ('CAN-0185', 'Canteen A', 'CANNED_DRINKS', 47, 'Active'),
  ('CAN-0185', 'Canteen B', 'CANNED_DRINKS', 47, 'Active'),
  ('CAN-0186', 'Canteen A', 'CANNED_DRINKS', 48, 'Active'),
  ('CAN-0186', 'Canteen B', 'CANNED_DRINKS', 48, 'Active'),
  ('CAN-0187', 'Canteen A', 'CANNED_DRINKS', 49, 'Active'),
  ('CAN-0187', 'Canteen B', 'CANNED_DRINKS', 49, 'Active'),
  ('CAN-0188', 'Canteen A', 'CANNED_DRINKS', 50, 'Active'),
  ('CAN-0188', 'Canteen B', 'CANNED_DRINKS', 50, 'Active'),
  ('CAN-0189', 'Canteen A', 'CANNED_DRINKS', 51, 'Active'),
  ('CAN-0189', 'Canteen B', 'CANNED_DRINKS', 51, 'Active'),
  ('CAN-0190', 'Canteen A', 'CANNED_DRINKS', 52, 'Active'),
  ('CAN-0190', 'Canteen B', 'CANNED_DRINKS', 52, 'Active'),
  ('CAN-0191', 'Canteen A', 'CANNED_DRINKS', 53, 'Active'),
  ('CAN-0191', 'Canteen B', 'CANNED_DRINKS', 53, 'Active'),
  ('CAN-0192', 'Canteen A', 'CANNED_DRINKS', 54, 'Active'),
  ('CAN-0192', 'Canteen B', 'CANNED_DRINKS', 54, 'Active'),
  ('CAN-0193', 'Canteen A', 'CANNED_DRINKS', 55, 'Active'),
  ('CAN-0193', 'Canteen B', 'CANNED_DRINKS', 55, 'Active'),
  ('CAN-0194', 'Canteen A', 'CANNED_DRINKS', 56, 'Active'),
  ('CAN-0194', 'Canteen B', 'CANNED_DRINKS', 56, 'Active'),
  ('CAN-0195', 'Canteen A', 'CANNED_DRINKS', 57, 'Active'),
  ('CAN-0195', 'Canteen B', 'CANNED_DRINKS', 57, 'Active'),
  ('CAN-0196', 'Canteen A', 'CANNED_DRINKS', 58, 'Active'),
  ('CAN-0196', 'Canteen B', 'CANNED_DRINKS', 58, 'Active'),
  ('CAN-0197', 'Canteen A', 'CANNED_DRINKS', 59, 'Active'),
  ('CAN-0197', 'Canteen B', 'CANNED_DRINKS', 59, 'Active'),
  ('CAN-0198', 'Canteen A', 'CANNED_DRINKS', 60, 'Active'),
  ('CAN-0198', 'Canteen B', 'CANNED_DRINKS', 60, 'Active'),
  ('CAN-0199', 'Canteen A', 'CANNED_DRINKS', 61, 'Active'),
  ('CAN-0199', 'Canteen B', 'CANNED_DRINKS', 61, 'Active'),
  ('CAN-0200', 'Canteen A', 'CANNED_DRINKS', 62, 'Active'),
  ('CAN-0200', 'Canteen B', 'CANNED_DRINKS', 62, 'Active'),
  ('CAN-0201', 'Canteen A', 'CANNED_DRINKS', 63, 'Active'),
  ('CAN-0201', 'Canteen B', 'CANNED_DRINKS', 63, 'Active'),
  ('CAN-0202', 'Canteen A', 'CANNED_DRINKS', 64, 'Active'),
  ('CAN-0202', 'Canteen B', 'CANNED_DRINKS', 64, 'Active'),
  ('CAN-0203', 'Canteen A', 'CANNED_DRINKS', 65, 'Active'),
  ('CAN-0203', 'Canteen B', 'CANNED_DRINKS', 65, 'Active'),
  ('CAN-0204', 'Canteen A', 'CANNED_DRINKS', 66, 'Active'),
  ('CAN-0204', 'Canteen B', 'CANNED_DRINKS', 66, 'Active'),
  ('CAN-0205', 'Canteen A', 'CANNED_DRINKS', 67, 'Active'),
  ('CAN-0205', 'Canteen B', 'CANNED_DRINKS', 67, 'Active'),
  ('CAN-0206', 'Canteen A', 'CANNED_DRINKS', 68, 'Active'),
  ('CAN-0206', 'Canteen B', 'CANNED_DRINKS', 68, 'Active'),
  ('CAN-0207', 'Canteen A', 'CANNED_DRINKS', 69, 'Active'),
  ('CAN-0207', 'Canteen B', 'CANNED_DRINKS', 69, 'Active'),
  ('CAN-0208', 'Canteen A', 'CANNED_DRINKS', 70, 'Active'),
  ('CAN-0208', 'Canteen B', 'CANNED_DRINKS', 70, 'Active'),
  ('CAN-0209', 'Canteen A', 'CANNED_DRINKS', 71, 'Active'),
  ('CAN-0209', 'Canteen B', 'CANNED_DRINKS', 71, 'Active'),
  ('CAN-0210', 'Canteen A', 'CANNED_DRINKS', 72, 'Active'),
  ('CAN-0210', 'Canteen B', 'CANNED_DRINKS', 72, 'Active'),
  ('CAN-0211', 'Canteen A', 'CANNED_DRINKS', 73, 'Active'),
  ('CAN-0211', 'Canteen B', 'CANNED_DRINKS', 73, 'Active'),
  ('CAN-0212', 'Canteen A', 'CANNED_DRINKS', 74, 'Active'),
  ('CAN-0212', 'Canteen B', 'CANNED_DRINKS', 74, 'Active'),
  ('CAN-0213', 'Canteen A', 'CANNED_DRINKS', 75, 'Active'),
  ('CAN-0213', 'Canteen B', 'CANNED_DRINKS', 75, 'Active'),
  ('CAN-0214', 'Canteen A', 'CANNED_DRINKS', 76, 'Active'),
  ('CAN-0214', 'Canteen B', 'CANNED_DRINKS', 76, 'Active'),
  ('CAN-0215', 'Canteen A', 'CANNED_DRINKS', 77, 'Active'),
  ('CAN-0215', 'Canteen B', 'CANNED_DRINKS', 77, 'Active'),
  ('CAN-0216', 'Canteen A', 'CANNED_DRINKS', 78, 'Active'),
  ('CAN-0216', 'Canteen B', 'CANNED_DRINKS', 78, 'Active'),
  ('CAN-0217', 'Canteen A', 'CANNED_DRINKS', 79, 'Active'),
  ('CAN-0217', 'Canteen B', 'CANNED_DRINKS', 79, 'Active'),
  ('CAN-0218', 'Canteen A', 'CANNED_DRINKS', 80, 'Active'),
  ('CAN-0218', 'Canteen B', 'CANNED_DRINKS', 80, 'Active'),
  ('CAN-0219', 'Canteen A', 'CANNED_DRINKS', 81, 'Active'),
  ('CAN-0219', 'Canteen B', 'CANNED_DRINKS', 81, 'Active'),
  ('CAN-0220', 'Canteen A', 'CANNED_DRINKS', 82, 'Active'),
  ('CAN-0220', 'Canteen B', 'CANNED_DRINKS', 82, 'Active'),
  ('CAN-0221', 'Canteen A', 'CANNED_DRINKS', 83, 'Active'),
  ('CAN-0221', 'Canteen B', 'CANNED_DRINKS', 83, 'Active'),
  ('CAN-0222', 'Canteen A', 'CANNED_DRINKS', 84, 'Active'),
  ('CAN-0222', 'Canteen B', 'CANNED_DRINKS', 84, 'Active'),
  ('CAN-0223', 'Canteen A', 'CANNED_DRINKS', 85, 'Active'),
  ('CAN-0223', 'Canteen B', 'CANNED_DRINKS', 85, 'Active'),
  ('CAN-0224', 'Canteen A', 'CANNED_DRINKS', 86, 'Active'),
  ('CAN-0224', 'Canteen B', 'CANNED_DRINKS', 86, 'Active'),
  ('CAN-0225', 'Canteen A', 'CANNED_DRINKS', 87, 'Active'),
  ('CAN-0225', 'Canteen B', 'CANNED_DRINKS', 87, 'Active'),
  ('CAN-0226', 'Canteen A', 'CANNED_DRINKS', 88, 'Active'),
  ('CAN-0226', 'Canteen B', 'CANNED_DRINKS', 88, 'Active'),
  ('CAN-0227', 'Canteen A', 'CANNED_DRINKS', 89, 'Active'),
  ('CAN-0227', 'Canteen B', 'CANNED_DRINKS', 89, 'Active'),
  ('CAN-0228', 'Canteen A', 'CANNED_DRINKS', 90, 'Active'),
  ('CAN-0228', 'Canteen B', 'CANNED_DRINKS', 90, 'Active'),
  ('CAN-0229', 'Canteen A', 'CANNED_DRINKS', 91, 'Active'),
  ('CAN-0229', 'Canteen B', 'CANNED_DRINKS', 91, 'Active'),
  ('CAN-0230', 'Canteen A', 'CANNED_DRINKS', 92, 'Active'),
  ('CAN-0230', 'Canteen B', 'CANNED_DRINKS', 92, 'Active'),
  ('CAN-0231', 'Canteen A', 'CANNED_DRINKS', 93, 'Active'),
  ('CAN-0231', 'Canteen B', 'CANNED_DRINKS', 93, 'Active'),
  ('CAN-0232', 'Canteen A', 'CANNED_DRINKS', 94, 'Active'),
  ('CAN-0232', 'Canteen B', 'CANNED_DRINKS', 94, 'Active'),
  ('CAN-0233', 'Canteen A', 'CANNED_DRINKS', 95, 'Active'),
  ('CAN-0233', 'Canteen B', 'CANNED_DRINKS', 95, 'Active'),
  ('CAN-0234', 'Canteen A', 'CANNED_DRINKS', 96, 'Active'),
  ('CAN-0234', 'Canteen B', 'CANNED_DRINKS', 96, 'Active'),
  ('CAN-0235', 'Canteen A', 'CANNED_DRINKS', 97, 'Active'),
  ('CAN-0235', 'Canteen B', 'CANNED_DRINKS', 97, 'Active'),
  ('CAN-0236', 'Canteen A', 'CANNED_DRINKS', 98, 'Active'),
  ('CAN-0236', 'Canteen B', 'CANNED_DRINKS', 98, 'Active'),
  ('CAN-0237', 'Canteen A', 'CANNED_DRINKS', 99, 'Active'),
  ('CAN-0237', 'Canteen B', 'CANNED_DRINKS', 99, 'Active'),
  ('CAN-0238', 'Canteen A', 'CANNED_DRINKS', 100, 'Active'),
  ('CAN-0238', 'Canteen B', 'CANNED_DRINKS', 100, 'Active'),
  ('CAN-0239', 'Canteen A', 'CANNED_DRINKS', 101, 'Active'),
  ('CAN-0239', 'Canteen B', 'CANNED_DRINKS', 101, 'Active'),
  ('CAN-0240', 'Canteen A', 'CANNED_DRINKS', 102, 'Active'),
  ('CAN-0240', 'Canteen B', 'CANNED_DRINKS', 102, 'Active'),
  ('CAN-0241', 'Canteen A', 'CANNED_DRINKS', 103, 'Active'),
  ('CAN-0241', 'Canteen B', 'CANNED_DRINKS', 103, 'Active'),
  ('CAN-0242', 'Canteen A', 'CANNED_DRINKS', 104, 'Active'),
  ('CAN-0242', 'Canteen B', 'CANNED_DRINKS', 104, 'Active'),
  ('CAN-0243', 'Canteen A', 'CANNED_DRINKS', 105, 'Active'),
  ('CAN-0243', 'Canteen B', 'CANNED_DRINKS', 105, 'Active'),
  ('CAN-0244', 'Canteen A', 'CANNED_DRINKS', 106, 'Active'),
  ('CAN-0244', 'Canteen B', 'CANNED_DRINKS', 106, 'Active'),
  ('CAN-0245', 'Canteen A', 'CANNED_DRINKS', 107, 'Active'),
  ('CAN-0245', 'Canteen B', 'CANNED_DRINKS', 107, 'Active'),
  ('CAN-0246', 'Canteen A', 'CANNED_DRINKS', 108, 'Active'),
  ('CAN-0246', 'Canteen B', 'CANNED_DRINKS', 108, 'Active'),
  ('CAN-0247', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 1, 'Active'),
  ('CAN-0247', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 1, 'Active'),
  ('CAN-0248', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 2, 'Active'),
  ('CAN-0248', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 2, 'Active'),
  ('CAN-0249', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 3, 'Active'),
  ('CAN-0249', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 3, 'Active'),
  ('CAN-0250', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 4, 'Active'),
  ('CAN-0250', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 4, 'Active'),
  ('CAN-0251', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 5, 'Active'),
  ('CAN-0251', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 5, 'Active'),
  ('CAN-0252', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 6, 'Active'),
  ('CAN-0252', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 6, 'Active'),
  ('CAN-0253', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 7, 'Active'),
  ('CAN-0253', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 7, 'Active'),
  ('CAN-0254', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 8, 'Active'),
  ('CAN-0254', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 8, 'Active'),
  ('CAN-0255', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 9, 'Active'),
  ('CAN-0255', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 9, 'Active'),
  ('CAN-0256', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 10, 'Active'),
  ('CAN-0256', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 10, 'Active'),
  ('CAN-0257', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 11, 'Active'),
  ('CAN-0257', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 11, 'Active'),
  ('CAN-0258', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 12, 'Active'),
  ('CAN-0258', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 12, 'Active'),
  ('CAN-0259', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 13, 'Active'),
  ('CAN-0259', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 13, 'Active'),
  ('CAN-0260', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 14, 'Active'),
  ('CAN-0260', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 14, 'Active'),
  ('CAN-0261', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 15, 'Active'),
  ('CAN-0261', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 15, 'Active'),
  ('CAN-0262', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 16, 'Active'),
  ('CAN-0262', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 16, 'Active'),
  ('CAN-0263', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 17, 'Active'),
  ('CAN-0263', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 17, 'Active'),
  ('CAN-0264', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 18, 'Active'),
  ('CAN-0264', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 18, 'Active'),
  ('CAN-0265', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 19, 'Active'),
  ('CAN-0265', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 19, 'Active'),
  ('CAN-0266', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 20, 'Active'),
  ('CAN-0266', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 20, 'Active'),
  ('CAN-0267', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 21, 'Active'),
  ('CAN-0267', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 21, 'Active'),
  ('CAN-0268', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 22, 'Active'),
  ('CAN-0268', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 22, 'Active'),
  ('CAN-0269', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 23, 'Active'),
  ('CAN-0269', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 23, 'Active'),
  ('CAN-0270', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 24, 'Active'),
  ('CAN-0270', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 24, 'Active'),
  ('CAN-0271', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 25, 'Active'),
  ('CAN-0271', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 25, 'Active'),
  ('CAN-0272', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 26, 'Active'),
  ('CAN-0272', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 26, 'Active'),
  ('CAN-0273', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 27, 'Active'),
  ('CAN-0273', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 27, 'Active'),
  ('CAN-0274', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 28, 'Active'),
  ('CAN-0274', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 28, 'Active'),
  ('CAN-0275', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 29, 'Active'),
  ('CAN-0275', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 29, 'Active'),
  ('CAN-0276', 'Canteen A', 'CELLOPHANE_HOUSEHOLD', 30, 'Active'),
  ('CAN-0276', 'Canteen B', 'CELLOPHANE_HOUSEHOLD', 30, 'Active'),
  ('CAN-0277', 'Canteen A', 'CANDIES_SNACKS', 1, 'Active'),
  ('CAN-0277', 'Canteen B', 'CANDIES_SNACKS', 1, 'Active'),
  ('CAN-0278', 'Canteen A', 'CANDIES_SNACKS', 2, 'Active'),
  ('CAN-0278', 'Canteen B', 'CANDIES_SNACKS', 2, 'Active'),
  ('CAN-0279', 'Canteen A', 'CANDIES_SNACKS', 3, 'Active'),
  ('CAN-0279', 'Canteen B', 'CANDIES_SNACKS', 3, 'Active'),
  ('CAN-0280', 'Canteen A', 'CANDIES_SNACKS', 4, 'Active'),
  ('CAN-0280', 'Canteen B', 'CANDIES_SNACKS', 4, 'Active'),
  ('CAN-0281', 'Canteen A', 'CANDIES_SNACKS', 5, 'Active'),
  ('CAN-0281', 'Canteen B', 'CANDIES_SNACKS', 5, 'Active'),
  ('CAN-0282', 'Canteen A', 'CANDIES_SNACKS', 6, 'Active'),
  ('CAN-0282', 'Canteen B', 'CANDIES_SNACKS', 6, 'Active'),
  ('CAN-0283', 'Canteen A', 'CANDIES_SNACKS', 7, 'Active'),
  ('CAN-0283', 'Canteen B', 'CANDIES_SNACKS', 7, 'Active'),
  ('CAN-0284', 'Canteen A', 'CANDIES_SNACKS', 8, 'Active'),
  ('CAN-0284', 'Canteen B', 'CANDIES_SNACKS', 8, 'Active'),
  ('CAN-0285', 'Canteen A', 'CANDIES_SNACKS', 9, 'Active'),
  ('CAN-0285', 'Canteen B', 'CANDIES_SNACKS', 9, 'Active'),
  ('CAN-0286', 'Canteen A', 'CANDIES_SNACKS', 10, 'Active'),
  ('CAN-0286', 'Canteen B', 'CANDIES_SNACKS', 10, 'Active'),
  ('CAN-0287', 'Canteen A', 'CANDIES_SNACKS', 11, 'Active'),
  ('CAN-0287', 'Canteen B', 'CANDIES_SNACKS', 11, 'Active'),
  ('CAN-0288', 'Canteen A', 'CANDIES_SNACKS', 12, 'Active'),
  ('CAN-0288', 'Canteen B', 'CANDIES_SNACKS', 12, 'Active'),
  ('CAN-0289', 'Canteen A', 'CANDIES_SNACKS', 13, 'Active'),
  ('CAN-0289', 'Canteen B', 'CANDIES_SNACKS', 13, 'Active'),
  ('CAN-0290', 'Canteen A', 'CANDIES_SNACKS', 14, 'Active'),
  ('CAN-0290', 'Canteen B', 'CANDIES_SNACKS', 14, 'Active'),
  ('CAN-0291', 'Canteen A', 'CANDIES_SNACKS', 15, 'Active'),
  ('CAN-0291', 'Canteen B', 'CANDIES_SNACKS', 15, 'Active'),
  ('CAN-0292', 'Canteen A', 'CANDIES_SNACKS', 16, 'Active'),
  ('CAN-0292', 'Canteen B', 'CANDIES_SNACKS', 16, 'Active'),
  ('CAN-0293', 'Canteen A', 'CANDIES_SNACKS', 17, 'Active'),
  ('CAN-0293', 'Canteen B', 'CANDIES_SNACKS', 17, 'Active'),
  ('CAN-0294', 'Canteen A', 'CANDIES_SNACKS', 18, 'Active'),
  ('CAN-0294', 'Canteen B', 'CANDIES_SNACKS', 18, 'Active'),
  ('CAN-0295', 'Canteen A', 'CANDIES_SNACKS', 19, 'Active'),
  ('CAN-0295', 'Canteen B', 'CANDIES_SNACKS', 19, 'Active'),
  ('CAN-0296', 'Canteen A', 'CANDIES_SNACKS', 20, 'Active'),
  ('CAN-0296', 'Canteen B', 'CANDIES_SNACKS', 20, 'Active'),
  ('CAN-0297', 'Canteen A', 'CANDIES_SNACKS', 21, 'Active'),
  ('CAN-0297', 'Canteen B', 'CANDIES_SNACKS', 21, 'Active'),
  ('CAN-0298', 'Canteen A', 'CANDIES_SNACKS', 22, 'Active'),
  ('CAN-0298', 'Canteen B', 'CANDIES_SNACKS', 22, 'Active'),
  ('CAN-0299', 'Canteen A', 'CANDIES_SNACKS', 23, 'Active'),
  ('CAN-0299', 'Canteen B', 'CANDIES_SNACKS', 23, 'Active'),
  ('CAN-0300', 'Canteen A', 'CANDIES_SNACKS', 24, 'Active'),
  ('CAN-0300', 'Canteen B', 'CANDIES_SNACKS', 24, 'Active'),
  ('CAN-0301', 'Canteen A', 'CANDIES_SNACKS', 25, 'Active'),
  ('CAN-0301', 'Canteen B', 'CANDIES_SNACKS', 25, 'Active'),
  ('CAN-0302', 'Canteen A', 'CANDIES_SNACKS', 26, 'Active'),
  ('CAN-0302', 'Canteen B', 'CANDIES_SNACKS', 26, 'Active'),
  ('CAN-0303', 'Canteen A', 'CANDIES_SNACKS', 27, 'Active'),
  ('CAN-0303', 'Canteen B', 'CANDIES_SNACKS', 27, 'Active'),
  ('CAN-0304', 'Canteen A', 'CANDIES_SNACKS', 28, 'Active'),
  ('CAN-0304', 'Canteen B', 'CANDIES_SNACKS', 28, 'Active'),
  ('CAN-0305', 'Canteen A', 'CANDIES_SNACKS', 29, 'Active'),
  ('CAN-0305', 'Canteen B', 'CANDIES_SNACKS', 29, 'Active'),
  ('CAN-0306', 'Canteen A', 'CANDIES_SNACKS', 30, 'Active'),
  ('CAN-0306', 'Canteen B', 'CANDIES_SNACKS', 30, 'Active'),
  ('CAN-0307', 'Canteen A', 'CANDIES_SNACKS', 31, 'Active'),
  ('CAN-0307', 'Canteen B', 'CANDIES_SNACKS', 31, 'Active'),
  ('CAN-0308', 'Canteen A', 'CANDIES_SNACKS', 32, 'Active'),
  ('CAN-0308', 'Canteen B', 'CANDIES_SNACKS', 32, 'Active'),
  ('CAN-0309', 'Canteen A', 'CANDIES_SNACKS', 33, 'Active'),
  ('CAN-0309', 'Canteen B', 'CANDIES_SNACKS', 33, 'Active'),
  ('CAN-0310', 'Canteen A', 'CANDIES_SNACKS', 34, 'Active'),
  ('CAN-0310', 'Canteen B', 'CANDIES_SNACKS', 34, 'Active'),
  ('CAN-0311', 'Canteen A', 'CANDIES_SNACKS', 35, 'Active'),
  ('CAN-0311', 'Canteen B', 'CANDIES_SNACKS', 35, 'Active'),
  ('CAN-0312', 'Canteen A', 'CANDIES_SNACKS', 36, 'Active'),
  ('CAN-0312', 'Canteen B', 'CANDIES_SNACKS', 36, 'Active'),
  ('CAN-0313', 'Canteen A', 'CANDIES_SNACKS', 37, 'Active'),
  ('CAN-0313', 'Canteen B', 'CANDIES_SNACKS', 37, 'Active'),
  ('CAN-0314', 'Canteen A', 'CANDIES_SNACKS', 38, 'Active'),
  ('CAN-0314', 'Canteen B', 'CANDIES_SNACKS', 38, 'Active'),
  ('CAN-0315', 'Canteen A', 'CANDIES_SNACKS', 39, 'Active'),
  ('CAN-0315', 'Canteen B', 'CANDIES_SNACKS', 39, 'Active'),
  ('CAN-0316', 'Canteen A', 'CANDIES_SNACKS', 40, 'Active'),
  ('CAN-0316', 'Canteen B', 'CANDIES_SNACKS', 40, 'Active'),
  ('CAN-0317', 'Canteen A', 'CANDIES_SNACKS', 41, 'Active'),
  ('CAN-0317', 'Canteen B', 'CANDIES_SNACKS', 41, 'Active'),
  ('CAN-0318', 'Canteen A', 'CANDIES_SNACKS', 42, 'Active'),
  ('CAN-0318', 'Canteen B', 'CANDIES_SNACKS', 42, 'Active'),
  ('CAN-0319', 'Canteen A', 'CANDIES_SNACKS', 43, 'Active'),
  ('CAN-0319', 'Canteen B', 'CANDIES_SNACKS', 43, 'Active'),
  ('CAN-0320', 'Canteen A', 'CANDIES_SNACKS', 44, 'Active'),
  ('CAN-0320', 'Canteen B', 'CANDIES_SNACKS', 44, 'Active'),
  ('CAN-0321', 'Canteen A', 'CANDIES_SNACKS', 45, 'Active'),
  ('CAN-0321', 'Canteen B', 'CANDIES_SNACKS', 45, 'Active'),
  ('CAN-0322', 'Canteen A', 'CANDIES_SNACKS', 46, 'Active'),
  ('CAN-0322', 'Canteen B', 'CANDIES_SNACKS', 46, 'Active'),
  ('CAN-0323', 'Canteen A', 'CANDIES_SNACKS', 47, 'Active'),
  ('CAN-0323', 'Canteen B', 'CANDIES_SNACKS', 47, 'Active'),
  ('CAN-0324', 'Canteen A', 'CANDIES_SNACKS', 48, 'Active'),
  ('CAN-0324', 'Canteen B', 'CANDIES_SNACKS', 48, 'Active'),
  ('CAN-0325', 'Canteen A', 'CANDIES_SNACKS', 49, 'Active'),
  ('CAN-0325', 'Canteen B', 'CANDIES_SNACKS', 49, 'Active'),
  ('CAN-0326', 'Canteen A', 'CANDIES_SNACKS', 50, 'Active'),
  ('CAN-0326', 'Canteen B', 'CANDIES_SNACKS', 50, 'Active'),
  ('CAN-0327', 'Canteen A', 'CANDIES_SNACKS', 51, 'Active'),
  ('CAN-0327', 'Canteen B', 'CANDIES_SNACKS', 51, 'Active'),
  ('CAN-0328', 'Canteen A', 'CANDIES_SNACKS', 52, 'Active'),
  ('CAN-0328', 'Canteen B', 'CANDIES_SNACKS', 52, 'Active'),
  ('CAN-0329', 'Canteen A', 'CANDIES_SNACKS', 53, 'Active'),
  ('CAN-0329', 'Canteen B', 'CANDIES_SNACKS', 53, 'Active'),
  ('CAN-0330', 'Canteen A', 'CANDIES_SNACKS', 54, 'Active'),
  ('CAN-0330', 'Canteen B', 'CANDIES_SNACKS', 54, 'Active'),
  ('CAN-0331', 'Canteen A', 'CANDIES_SNACKS', 55, 'Active'),
  ('CAN-0331', 'Canteen B', 'CANDIES_SNACKS', 55, 'Active'),
  ('CAN-0332', 'Canteen A', 'CANDIES_SNACKS', 56, 'Active'),
  ('CAN-0332', 'Canteen B', 'CANDIES_SNACKS', 56, 'Active'),
  ('CAN-0333', 'Canteen A', 'CANDIES_SNACKS', 57, 'Active'),
  ('CAN-0333', 'Canteen B', 'CANDIES_SNACKS', 57, 'Active'),
  ('CAN-0334', 'Canteen A', 'CANDIES_SNACKS', 58, 'Active'),
  ('CAN-0334', 'Canteen B', 'CANDIES_SNACKS', 58, 'Active'),
  ('CAN-0335', 'Canteen A', 'CANDIES_SNACKS', 59, 'Active'),
  ('CAN-0335', 'Canteen B', 'CANDIES_SNACKS', 59, 'Active'),
  ('CAN-0336', 'Canteen A', 'CANDIES_SNACKS', 60, 'Active'),
  ('CAN-0336', 'Canteen B', 'CANDIES_SNACKS', 60, 'Active'),
  ('CAN-0337', 'Canteen A', 'CANDIES_SNACKS', 61, 'Active'),
  ('CAN-0337', 'Canteen B', 'CANDIES_SNACKS', 61, 'Active'),
  ('CAN-0338', 'Canteen A', 'CANDIES_SNACKS', 62, 'Active'),
  ('CAN-0338', 'Canteen B', 'CANDIES_SNACKS', 62, 'Active'),
  ('CAN-0339', 'Canteen A', 'CANDIES_SNACKS', 63, 'Active'),
  ('CAN-0339', 'Canteen B', 'CANDIES_SNACKS', 63, 'Active'),
  ('CAN-0340', 'Canteen A', 'CANDIES_SNACKS', 64, 'Active'),
  ('CAN-0340', 'Canteen B', 'CANDIES_SNACKS', 64, 'Active'),
  ('CAN-0341', 'Canteen A', 'CANDIES_SNACKS', 65, 'Active'),
  ('CAN-0341', 'Canteen B', 'CANDIES_SNACKS', 65, 'Active'),
  ('CAN-0342', 'Canteen A', 'CANDIES_SNACKS', 66, 'Active'),
  ('CAN-0342', 'Canteen B', 'CANDIES_SNACKS', 66, 'Active'),
  ('CAN-0343', 'Canteen A', 'CANDIES_SNACKS', 67, 'Active'),
  ('CAN-0343', 'Canteen B', 'CANDIES_SNACKS', 67, 'Active'),
  ('CAN-0344', 'Canteen A', 'CANDIES_SNACKS', 68, 'Active'),
  ('CAN-0344', 'Canteen B', 'CANDIES_SNACKS', 68, 'Active'),
  ('CAN-0345', 'Canteen A', 'CANDIES_SNACKS', 69, 'Active'),
  ('CAN-0345', 'Canteen B', 'CANDIES_SNACKS', 69, 'Active'),
  ('CAN-0346', 'Canteen A', 'CANDIES_SNACKS', 70, 'Active'),
  ('CAN-0346', 'Canteen B', 'CANDIES_SNACKS', 70, 'Active'),
  ('CAN-0347', 'Canteen A', 'CANDIES_SNACKS', 71, 'Active'),
  ('CAN-0347', 'Canteen B', 'CANDIES_SNACKS', 71, 'Active'),
  ('CAN-0348', 'Canteen A', 'CANDIES_SNACKS', 72, 'Active'),
  ('CAN-0348', 'Canteen B', 'CANDIES_SNACKS', 72, 'Active'),
  ('CAN-0349', 'Canteen A', 'CANDIES_SNACKS', 73, 'Active'),
  ('CAN-0349', 'Canteen B', 'CANDIES_SNACKS', 73, 'Active'),
  ('CAN-0350', 'Canteen A', 'CANDIES_SNACKS', 74, 'Active'),
  ('CAN-0350', 'Canteen B', 'CANDIES_SNACKS', 74, 'Active'),
  ('CAN-0351', 'Canteen A', 'CANDIES_SNACKS', 75, 'Active'),
  ('CAN-0351', 'Canteen B', 'CANDIES_SNACKS', 75, 'Active'),
  ('CAN-0352', 'Canteen A', 'CANDIES_SNACKS', 76, 'Active'),
  ('CAN-0352', 'Canteen B', 'CANDIES_SNACKS', 76, 'Active'),
  ('CAN-0353', 'Canteen A', 'CANDIES_SNACKS', 77, 'Active'),
  ('CAN-0353', 'Canteen B', 'CANDIES_SNACKS', 77, 'Active'),
  ('CAN-0354', 'Canteen A', 'CANDIES_SNACKS', 78, 'Active'),
  ('CAN-0354', 'Canteen B', 'CANDIES_SNACKS', 78, 'Active'),
  ('CAN-0355', 'Canteen A', 'CANDIES_SNACKS', 79, 'Active'),
  ('CAN-0355', 'Canteen B', 'CANDIES_SNACKS', 79, 'Active'),
  ('CAN-0356', 'Canteen A', 'CANDIES_SNACKS', 80, 'Active'),
  ('CAN-0356', 'Canteen B', 'CANDIES_SNACKS', 80, 'Active'),
  ('CAN-0357', 'Canteen A', 'BISCUITS', 1, 'Active'),
  ('CAN-0357', 'Canteen B', 'BISCUITS', 1, 'Active'),
  ('CAN-0358', 'Canteen A', 'BISCUITS', 2, 'Active'),
  ('CAN-0358', 'Canteen B', 'BISCUITS', 2, 'Active'),
  ('CAN-0359', 'Canteen A', 'BISCUITS', 3, 'Active'),
  ('CAN-0359', 'Canteen B', 'BISCUITS', 3, 'Active'),
  ('CAN-0360', 'Canteen A', 'BISCUITS', 4, 'Active'),
  ('CAN-0360', 'Canteen B', 'BISCUITS', 4, 'Active'),
  ('CAN-0361', 'Canteen A', 'BISCUITS', 5, 'Active'),
  ('CAN-0361', 'Canteen B', 'BISCUITS', 5, 'Active'),
  ('CAN-0362', 'Canteen A', 'BISCUITS', 6, 'Active'),
  ('CAN-0362', 'Canteen B', 'BISCUITS', 6, 'Active'),
  ('CAN-0363', 'Canteen A', 'BISCUITS', 7, 'Active'),
  ('CAN-0363', 'Canteen B', 'BISCUITS', 7, 'Active'),
  ('CAN-0364', 'Canteen A', 'BISCUITS', 8, 'Active'),
  ('CAN-0364', 'Canteen B', 'BISCUITS', 8, 'Active'),
  ('CAN-0365', 'Canteen A', 'BISCUITS', 9, 'Active'),
  ('CAN-0365', 'Canteen B', 'BISCUITS', 9, 'Active'),
  ('CAN-0366', 'Canteen A', 'BISCUITS', 10, 'Active'),
  ('CAN-0366', 'Canteen B', 'BISCUITS', 10, 'Active'),
  ('CAN-0367', 'Canteen A', 'BISCUITS', 11, 'Active'),
  ('CAN-0367', 'Canteen B', 'BISCUITS', 11, 'Active'),
  ('CAN-0368', 'Canteen A', 'BISCUITS', 12, 'Active'),
  ('CAN-0368', 'Canteen B', 'BISCUITS', 12, 'Active'),
  ('CAN-0369', 'Canteen A', 'BISCUITS', 13, 'Active'),
  ('CAN-0369', 'Canteen B', 'BISCUITS', 13, 'Active'),
  ('CAN-0370', 'Canteen A', 'BISCUITS', 14, 'Active'),
  ('CAN-0370', 'Canteen B', 'BISCUITS', 14, 'Active'),
  ('CAN-0371', 'Canteen A', 'BISCUITS', 15, 'Active'),
  ('CAN-0371', 'Canteen B', 'BISCUITS', 15, 'Active'),
  ('CAN-0372', 'Canteen A', 'BISCUITS', 16, 'Active'),
  ('CAN-0372', 'Canteen B', 'BISCUITS', 16, 'Active'),
  ('CAN-0373', 'Canteen A', 'BISCUITS', 17, 'Active'),
  ('CAN-0373', 'Canteen B', 'BISCUITS', 17, 'Active'),
  ('CAN-0374', 'Canteen A', 'BISCUITS', 18, 'Active'),
  ('CAN-0374', 'Canteen B', 'BISCUITS', 18, 'Active'),
  ('CAN-0375', 'Canteen A', 'BISCUITS', 19, 'Active'),
  ('CAN-0375', 'Canteen B', 'BISCUITS', 19, 'Active'),
  ('CAN-0376', 'Canteen A', 'BISCUITS', 20, 'Active'),
  ('CAN-0376', 'Canteen B', 'BISCUITS', 20, 'Active'),
  ('CAN-0377', 'Canteen A', 'BISCUITS', 21, 'Active'),
  ('CAN-0377', 'Canteen B', 'BISCUITS', 21, 'Active'),
  ('CAN-0378', 'Canteen A', 'BISCUITS', 22, 'Active'),
  ('CAN-0378', 'Canteen B', 'BISCUITS', 22, 'Active'),
  ('CAN-0379', 'Canteen A', 'BISCUITS', 23, 'Active'),
  ('CAN-0379', 'Canteen B', 'BISCUITS', 23, 'Active'),
  ('CAN-0380', 'Canteen A', 'BISCUITS', 24, 'Active'),
  ('CAN-0380', 'Canteen B', 'BISCUITS', 24, 'Active'),
  ('CAN-0381', 'Canteen A', 'BISCUITS', 25, 'Active'),
  ('CAN-0381', 'Canteen B', 'BISCUITS', 25, 'Active'),
  ('CAN-0382', 'Canteen A', 'BISCUITS', 26, 'Active'),
  ('CAN-0382', 'Canteen B', 'BISCUITS', 26, 'Active'),
  ('CAN-0383', 'Canteen A', 'BISCUITS', 27, 'Active'),
  ('CAN-0383', 'Canteen B', 'BISCUITS', 27, 'Active'),
  ('CAN-0384', 'Canteen A', 'BISCUITS', 28, 'Active'),
  ('CAN-0384', 'Canteen B', 'BISCUITS', 28, 'Active'),
  ('CAN-0385', 'Canteen A', 'BISCUITS', 29, 'Active'),
  ('CAN-0385', 'Canteen B', 'BISCUITS', 29, 'Active'),
  ('CAN-0386', 'Canteen A', 'BISCUITS', 30, 'Active'),
  ('CAN-0386', 'Canteen B', 'BISCUITS', 30, 'Active'),
  ('CAN-0387', 'Canteen A', 'BISCUITS', 31, 'Active'),
  ('CAN-0387', 'Canteen B', 'BISCUITS', 31, 'Active'),
  ('CAN-0388', 'Canteen A', 'BISCUITS', 32, 'Active'),
  ('CAN-0388', 'Canteen B', 'BISCUITS', 32, 'Active'),
  ('CAN-0389', 'Canteen A', 'BISCUITS', 33, 'Active'),
  ('CAN-0389', 'Canteen B', 'BISCUITS', 33, 'Active'),
  ('CAN-0390', 'Canteen A', 'BISCUITS', 34, 'Active'),
  ('CAN-0390', 'Canteen B', 'BISCUITS', 34, 'Active'),
  ('CAN-0391', 'Canteen A', 'BISCUITS', 35, 'Active'),
  ('CAN-0391', 'Canteen B', 'BISCUITS', 35, 'Active'),
  ('CAN-0392', 'Canteen A', 'BISCUITS', 36, 'Active'),
  ('CAN-0392', 'Canteen B', 'BISCUITS', 36, 'Active'),
  ('CAN-0393', 'Canteen A', 'BISCUITS', 37, 'Active'),
  ('CAN-0393', 'Canteen B', 'BISCUITS', 37, 'Active'),
  ('CAN-0394', 'Canteen A', 'BISCUITS', 38, 'Active'),
  ('CAN-0394', 'Canteen B', 'BISCUITS', 38, 'Active'),
  ('CAN-0395', 'Canteen A', 'BISCUITS', 39, 'Active'),
  ('CAN-0395', 'Canteen B', 'BISCUITS', 39, 'Active'),
  ('CAN-0396', 'Canteen A', 'BISCUITS', 40, 'Active'),
  ('CAN-0396', 'Canteen B', 'BISCUITS', 40, 'Active'),
  ('CAN-0397', 'Canteen A', 'BISCUITS', 41, 'Active'),
  ('CAN-0397', 'Canteen B', 'BISCUITS', 41, 'Active'),
  ('CAN-0398', 'Canteen A', 'BISCUITS', 42, 'Active'),
  ('CAN-0398', 'Canteen B', 'BISCUITS', 42, 'Active'),
  ('CAN-0399', 'Canteen A', 'BISCUITS', 43, 'Active'),
  ('CAN-0399', 'Canteen B', 'BISCUITS', 43, 'Active'),
  ('CAN-0400', 'Canteen A', 'BISCUITS', 44, 'Active'),
  ('CAN-0400', 'Canteen B', 'BISCUITS', 44, 'Active'),
  ('CAN-0401', 'Canteen A', 'BISCUITS', 45, 'Active'),
  ('CAN-0401', 'Canteen B', 'BISCUITS', 45, 'Active'),
  ('CAN-0402', 'Canteen A', 'BISCUITS', 46, 'Active'),
  ('CAN-0402', 'Canteen B', 'BISCUITS', 46, 'Active'),
  ('CAN-0403', 'Canteen A', 'BISCUITS', 47, 'Active'),
  ('CAN-0403', 'Canteen B', 'BISCUITS', 47, 'Active'),
  ('CAN-0404', 'Canteen A', 'BISCUITS', 48, 'Active'),
  ('CAN-0404', 'Canteen B', 'BISCUITS', 48, 'Active'),
  ('CAN-0405', 'Canteen A', 'BISCUITS', 49, 'Active'),
  ('CAN-0405', 'Canteen B', 'BISCUITS', 49, 'Active'),
  ('CAN-0406', 'Canteen A', 'BISCUITS', 50, 'Active'),
  ('CAN-0406', 'Canteen B', 'BISCUITS', 50, 'Active'),
  ('CAN-0407', 'Canteen A', 'BISCUITS', 51, 'Active'),
  ('CAN-0407', 'Canteen B', 'BISCUITS', 51, 'Active'),
  ('CAN-0408', 'Canteen A', 'BISCUITS', 52, 'Active'),
  ('CAN-0408', 'Canteen B', 'BISCUITS', 52, 'Active'),
  ('CAN-0409', 'Canteen A', 'BISCUITS', 53, 'Active'),
  ('CAN-0409', 'Canteen B', 'BISCUITS', 53, 'Active'),
  ('CAN-0410', 'Canteen A', 'BISCUITS', 54, 'Active'),
  ('CAN-0410', 'Canteen B', 'BISCUITS', 54, 'Active'),
  ('CAN-0411', 'Canteen A', 'BISCUITS', 55, 'Active'),
  ('CAN-0411', 'Canteen B', 'BISCUITS', 55, 'Active'),
  ('CAN-0412', 'Canteen A', 'BISCUITS', 56, 'Active'),
  ('CAN-0412', 'Canteen B', 'BISCUITS', 56, 'Active'),
  ('CAN-0413', 'Canteen A', 'BISCUITS', 57, 'Active'),
  ('CAN-0413', 'Canteen B', 'BISCUITS', 57, 'Active'),
  ('CAN-0414', 'Canteen A', 'BISCUITS', 58, 'Active'),
  ('CAN-0414', 'Canteen B', 'BISCUITS', 58, 'Active'),
  ('CAN-0415', 'Canteen A', 'BISCUITS', 59, 'Active'),
  ('CAN-0415', 'Canteen B', 'BISCUITS', 59, 'Active'),
  ('CAN-0416', 'Canteen A', 'BISCUITS', 60, 'Active'),
  ('CAN-0416', 'Canteen B', 'BISCUITS', 60, 'Active'),
  ('CAN-0417', 'Canteen A', 'BISCUITS', 61, 'Active'),
  ('CAN-0417', 'Canteen B', 'BISCUITS', 61, 'Active'),
  ('CAN-0418', 'Canteen A', 'BISCUITS', 62, 'Active'),
  ('CAN-0418', 'Canteen B', 'BISCUITS', 62, 'Active'),
  ('CAN-0419', 'Canteen A', 'BISCUITS', 63, 'Active'),
  ('CAN-0419', 'Canteen B', 'BISCUITS', 63, 'Active'),
  ('CAN-0420', 'Canteen A', 'BISCUITS', 64, 'Active'),
  ('CAN-0420', 'Canteen B', 'BISCUITS', 64, 'Active'),
  ('CAN-0421', 'Canteen A', 'BISCUITS', 65, 'Active'),
  ('CAN-0421', 'Canteen B', 'BISCUITS', 65, 'Active'),
  ('CAN-0422', 'Canteen A', 'KITCHEN_CONDIMENTS', 1, 'Active'),
  ('CAN-0422', 'Canteen B', 'KITCHEN_CONDIMENTS', 1, 'Active'),
  ('CAN-0423', 'Canteen A', 'KITCHEN_CONDIMENTS', 2, 'Active'),
  ('CAN-0423', 'Canteen B', 'KITCHEN_CONDIMENTS', 2, 'Active'),
  ('CAN-0424', 'Canteen A', 'KITCHEN_CONDIMENTS', 3, 'Active'),
  ('CAN-0424', 'Canteen B', 'KITCHEN_CONDIMENTS', 3, 'Active'),
  ('CAN-0425', 'Canteen A', 'KITCHEN_CONDIMENTS', 4, 'Active'),
  ('CAN-0425', 'Canteen B', 'KITCHEN_CONDIMENTS', 4, 'Active'),
  ('CAN-0426', 'Canteen A', 'KITCHEN_CONDIMENTS', 5, 'Active'),
  ('CAN-0426', 'Canteen B', 'KITCHEN_CONDIMENTS', 5, 'Active')
ON CONFLICT (item_code, location) DO UPDATE SET category_code = EXCLUDED.category_code, display_order = EXCLUDED.display_order, status = 'Active';
